### ISSUE TITLE
Первое мероприятие

### ISSUE THREAD

**Issue by marinintim** [nodeschool/spb#1]
Leave a comment if you're interested in attending.

Date TBA

**Comment by marinintim** [comment]
@ipelekhan @vkfont

**Comment by ipelekhan** [comment]
@marinintim, как дела? :-]

**Comment by border-radius** [comment]
Записываюсь.

**Comment by marinintim** [comment]
@border-radius: отлично! :)

@ipelekhan: надо как-нибудь встретиться.

**Comment by ipelekhan** [comment]
@marinintim не вопрос, отписал тебе в vk.

**Comment by martinheidegger** [comment]
Hey guys (sorry for writing in english, no russian available): @marinintim signed you up for the International day but I can't find an event sign-up page?! : https://github.com/nodeschool/international-day/issues/22

**Comment by iancrowther** [comment]
is this event still happening?

**Comment by ipelekhan** [comment]
@martinheidegger @iancrowther 
Sorry for the late reply. Saint Petersburg team will not be able to attend the event for various reasons this time. Should we cancel our enrollment somehow or this comment is enough? Thanks in advance.

**Comment by iancrowther** [comment]
@ipelekhan I have un-enrolled you.  sorry to see you go..  you were representing Russia man :-)

**Comment by marinintim** [comment]
Закрываю в пользу #6
