### ISSUE TITLE
Нодскул 21.06

### ISSUE THREAD

**Issue by marinintim** [nodeschool/spb#10]
Место: Epic Skills на Чкаловском, 15.

В этот раз нодскул будет тематическим, про асинхронность: разберёмся с коллбэками, промисами (cc: @vlkosinov) и генераторами (cc: @isRuslan). Но, конечно, можно и просто так прийти и узнать про ноду.

cc: @ipelekhan
// Всем от-cc-ченым предлагаю отписать тут же, сможете или нет.

**Comment by yamstr** [comment]
Я буду!

**Comment by Margolin96** [comment]
Скорее да, чем нет :)

**Comment by ipelekhan** [comment]
Смогу, буду рассказывать как установить git-bash на винде ;-)

**Comment by isRuslan** [comment]
Смогу, подготовлю перевод на русский язык :)

**Comment by Gurylev** [comment]
Хорошо, что не 20, в день webstandartdays. Буду.

**Comment by marinintim** [comment]
@Gurylev я туда и сам иду (:

**Comment by vkfont** [comment]
+1

**Comment by illyar80** [comment]
Да.

2015-06-10 14:29 GMT+03:00 afoninsky <notifications@github.com>:

**Comment by bezrukov** [comment]
буду:)

**Comment by luxeon89** [comment]
а по времени как?

**Comment by marinintim** [comment]
@luxeon89 так же, 14:00

**Comment by ida-t** [comment]
+1

**Comment by onmoon** [comment]
Если возможно придти без ноута, послушать, то также хотелось бы.

**Comment by suevalov** [comment]
+1

**Comment by marinintim** [comment]
@onmoon без ноутбука будет, как мне кажется, немного скучно, но прогонять не будет.

**Comment by small-fish** [comment]
+1

**Comment by gossoudarev** [comment]
А вы точно не прогоните? Тогда +1

**Comment by nzhukov** [comment]
+1

**Comment by pavelaks** [comment]
Запишите меня, пожалуйста!

**Comment by gbezyuk** [comment]
I'll probably be there.

**Comment by RoTerentev** [comment]
+1

**Comment by fual** [comment]
буду

**Comment by vlkosinov** [comment]
не отвечал, потому что не уверен был, смогу ли прийти. не смогу в это воскресенье никак:(

**Comment by RoTerentev** [comment]
-1

**Comment by Gurylev** [comment]
-1, заболел(

**Comment by marinintim** [comment]
@Gurylev, @vlkosinov, @RoTerentev: жаль :(

**Comment by gcheshkov** [comment]
:rocket:

**Comment by gossoudarev** [comment]
event.success();

**Comment by marinintim** [comment]
Спасибо всем, кто пришёл, ссылка на форму фидбека: [](https://docs.google.com/forms/d/1Olu6M-_-BGq7STCtgzAZ2C6tGwU6hhTL6euw61zF7uw/viewform)

**Comment by marinintim** [comment]
Закрытая issue не запрещает комментить, а служит индикатором того, что мероприятие прошло. :panda_face:

**Comment by olegshilov** [comment]
когда следующий ивент?
