### ISSUE TITLE
23 августа 2015

### ISSUE THREAD

**Issue by marinintim** [nodeschool/spb#12]
23 августа, 14:00, помещение школы веб-технологий Epic Skills (Чкаловский проспект, 15)

С собой нужно взять ноутбук.

В этот раз основной темой будут веб-фреймворки.

Организаторы: @marinintim, @glukki.

/cc @vkfont ?

**Comment by glukki** [comment]
Привет, я вроде опытен в ноде, помочь чем-нибудь? :)

**Comment by Gurylev** [comment]
+

**Comment by Broote** [comment]
+
