### ISSUE TITLE
27 сентября 2015 года

### ISSUE THREAD

**Issue by marinintim** [nodeschool/spb#14]
Сбор: **13:30**
Начало урока: **14:00**
Адрес: БЦ Бенуа, Пискарёвский пр., 2, к. 2
Как добраться: https://goo.gl/LSiS3w
Внутри: 5 этаж, Яндекс
Менторы: @marinintim, @glukki, @ipelekhan, @vkfont, @h4, @agufranov.
Вход по предварительной регистрации.
Список зарегистрировавшихся: [ниже](https://github.com/nodeschool/spb/issues/14#issuecomment-143232909)
Ограничение: 90 человек

Мероприятие для новичков, мы пройдём базовые уроки nodeschool.io (это такие наборы заданий):
- `javascripting` посвящён азам javascript,
- `learnyounode` — введение в node.js,
- `stream-adventure` научит работе со стримами,
- `git-it` поможет освоить git.

После этого мы напишем своих телеграм-ботов на node.js, используя внешние источники данных. 

Необходимо:

1. взять с собой ноутбук;
2. взять с собой паспорт/права для охраны;
3. зарегистрироваться на гитхабе;
4. зарегистрироваться в Телеграме.

А еще у нас есть группа ВК, в которую можно вступать: https://vk.com/nodeschool_spb :)

[**UPDATE 1**](https://github.com/nodeschool/spb/issues/14#issuecomment-140866536)
[**UPDATE 2**](https://github.com/nodeschool/spb/issues/14#issuecomment-141697245)
[**UPDATE 3**](https://github.com/nodeschool/spb/issues/14#issuecomment-141820403)
[**UPDATE 4**](https://github.com/nodeschool/spb/issues/14#issuecomment-143232909)

**Comment by h4** [comment]
:+1:

**Comment by ipelekhan** [comment]
:+1:

**Comment by glukki** [comment]
:+1:

**Comment by matiunin** [comment]
Вот если совсем не знаком, с этим, есть смысл приходить?

**Comment by h4** [comment]
@matiunin если хочется познакомиться — обязательно!

**Comment by matiunin** [comment]
окей, тогда я тоже :+1:

**Comment by aglalit** [comment]
Во сколько начало?

**Comment by marinintim** [comment]
@aglalit: в два часа дня, как обычно.

**Comment by aalexeev239** [comment]
:+1:
@marinintim а где проводится, обычно?

**Comment by pvf** [comment]
:+1: будет возможность ES6 поднять? каков формат проведения и где это находится?)

**Comment by marinintim** [comment]
@pvf: поясни, что значит «ES6 поднять»? Бабель поднимем, если что.
@aalexeev239: про место чуть позже уточним, _обычно_ (да и скорее всего и в этот раз) это Epic Skills на Чкаловском, 15.

**Comment by pvf** [comment]
@marinintim синтаксис и плюсы/минусы его реального применения)

**Comment by mishcherin** [comment]
впишусь :+1:

**Comment by vganshin** [comment]
:thumbsup:

**Comment by 7rulnik** [comment]
Не уверен, что смогу, но хотел бы придти.

**Comment by eliseealex** [comment]
:+1:

**Comment by ishaba** [comment]
:+1:

**Comment by dmitrylebedev** [comment]
:+1:

**Comment by Capitan-vi** [comment]
:+1:

**Comment by mostalt** [comment]
:+1:

**Comment by AnnaMukhina** [comment]
:thumbsup:

**Comment by Margolin96** [comment]
:thumbsup:

**Comment by evakerrigan** [comment]
![image](https://cloud.githubusercontent.com/assets/6607156/9857999/ab72aac4-5b26-11e5-8ec1-6a2464bf95d3.png)

**Comment by Meao** [comment]
Я совсем новичок. Нужно ли установить что-либо для написания кода? Что именно используется на макбуках?

**Comment by marinintim** [comment]
@Meao: потребуется какой-никакой редактор и нода. Если стоит brew, то поставить ноду очень просто.

Редактор — очень холиварная тема, подойдёт любой на вкус.

**Comment by danilapisarev** [comment]
+

**Comment by nicothin** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by TemaMix** [comment]
:+1:

**Comment by Ca4tkin** [comment]
:+1:

**Comment by dmglazunov** [comment]
:+1:

**Comment by midler** [comment]
:+1:

**Comment by kuksikus** [comment]
А сколько примерно по времени это длится?

**Comment by marinintim** [comment]
@kuksikus: прошлые три мероприятия проходили по четыре часа, в этот раз, может быть, чуть дольше.

**Comment by chakzefir** [comment]
:+1:

**Comment by XeL077** [comment]
:+1:

**Comment by sleepydisaster** [comment]
:+1:

**Comment by nastja-igel** [comment]
:+1:

**Comment by dmglazunov** [comment]
Это платно?

**Comment by marinintim** [comment]
@dmglazunov: это бесплатно, но можно захватить печеньки к чаю.

**Comment by etki** [comment]
:+1:

**Comment by amel-true** [comment]
:+1:

**Comment by dmglazunov** [comment]
@marinintim:  awesome!

**Comment by lunarlynx** [comment]
:+1:

**Comment by marsoupilamie** [comment]
![image](https://cloud.githubusercontent.com/assets/7814546/9874017/49e89d1e-5bac-11e5-96c2-4db0b19211da.png)

**Comment by ierhyna** [comment]
:+1:

**Comment by numfin** [comment]
Запись на YT будет? Вот не живу в Питере, ну прям оч хочется.

**Comment by invinsible** [comment]
:+1:

**Comment by zolotyh** [comment]
(y)

**Comment by fullgod** [comment]
:+1:

**Comment by UeberSlowpoke** [comment]
![1f44d](https://cloud.githubusercontent.com/assets/8135657/9874704/d2c929ec-5bb0-11e5-8415-d8310c0669d1.png)

**Comment by eteries** [comment]
:+1:

**Comment by UeberSlowpoke** [comment]
:+1:

**Comment by AndreyKopylov** [comment]
👍

**Comment by h4** [comment]
@numfin это сессия учебных заданий, а не лекции/доклады. Так что записывать особо нечего.

**Comment by bayguzin** [comment]
👍

**Comment by whois42** [comment]
👍🏿

**Comment by Nikita87200** [comment]
:+1:

**Comment by YanLobat** [comment]
:+1:

**Comment by etokareva** [comment]
:+1:

**Comment by pheophanna** [comment]
:+1:

**Comment by yamstr** [comment]
:+1:

**Comment by fual** [comment]
:+1:

**Comment by Gaserd** [comment]
:+1:

**Comment by agufranov** [comment]
:+1:

**Comment by YeS71** [comment]
Чтож я не в Питере!

**Comment by Voebro** [comment]
:+1:

**Comment by codeturn** [comment]
:+1:

**Comment by cakeinpanic** [comment]
и я приду

**Comment by Tuscen** [comment]
:+1:

**Comment by Oleg-docent** [comment]
:+1:   У меня на ноуте винда 8.1 и linux mint 17 на virtual box.  Наверно лучше на  линуксе кодить?

**Comment by marinintim** [comment]
@Oleg-docent: где вам удобнее. Но на винде вам понадобится сторонний терминал: говорят, что cmder неплох.

**Comment by Oleg-docent** [comment]
@marinintim понятно)  Вообще на линуксе проще , но кое-где сложности были, не все устанавливалось... Но об этом уже на встрече по ходу выполнения заданий

**Comment by core01** [comment]
:thumbsup: :point_up:

**Comment by arthique** [comment]
:+1:

**Comment by empas** [comment]
:+1:

**Comment by Enkil** [comment]
:+1:

**Comment by fresk-nc** [comment]
:+1:

**Comment by arcticmanic** [comment]
:+1:

**Comment by playlikednb** [comment]
:+1:

**Comment by enjidevelop** [comment]
:+1:

**Comment by AlexeySmolyakov** [comment]
:+1:

**Comment by MhMadHamster** [comment]
:+1:

**Comment by volvap** [comment]
:+1:

**Comment by odinsy** [comment]
:+1:
Кажется, мы не вместимся :)

**Comment by glukki** [comment]
@odinsy ничего, есть пара идей :)

**Comment by KleinenberG** [comment]
+1

**Comment by catangens** [comment]
![image](https://cloud.githubusercontent.com/assets/14318755/9915482/010d9eea-5cc0-11e5-88e7-d3501b45c74b.png)

**Comment by marinintim** [comment]
**UPDATE**:
Уважаемые участники, мы начинаем упираться в размеры площадки и сверхчеловеческие возможности менторов. По этой причине нам придется изменить место проведения, и ограничить количество участников.
Мы сможем провести этот урок для 90 человек, счетчик можно наблюдать справа →
Если вы не сможете прийти на мероприятие, пожалуйста, удалите свой комментарий с :+1:, чтобы освободить место другим желающим.

Если мы перевалим за 90 человек, обещаем провести этот урок повторно :)

**Comment by aglalit** [comment]
👍🏼

**Comment by francheskodelakoni** [comment]
https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png

**Comment by francheskodelakoni** [comment]
![shake](https://cloud.githubusercontent.com/assets/9852988/9917001/125978f6-5cc8-11e5-90dc-ae03ae972c45.png)

**Comment by aglalit** [comment]
:+1:

**Comment by Realetive** [comment]
:+1:

**Comment by MaceEsina** [comment]
👍🏿

**Comment by permidon** [comment]
:+1:

**Comment by KleinenberG** [comment]
а не много ли 90 человек?модет стоит уже разделить на группы, человек по 30 хотя бы, нет?
слишком большая аудитория для обучающего занятия.

**Comment by ipelekhan** [comment]
@KleinenberG, на самом деле 90 человек не много. Как уже было сказано выше, занятие будет не "обучающее", а, если можно так выразиться, "самообучающее". Менторы будут помогать тем, у кого что-то совсем не выходит по тем или иным причинам. Ну и кроме того поощряется взаимопомощь. Кто-то будет выполнять задания быстрее, они тоже смогут помогать разобраться с возникшими проблемами. Лекций или "написания функций под диктовку" у нас не будет, так что 90 человек вполне себе подъемная аудитория... хотя да, печенек на кофебрейке может хватить не всем, но мы работаем над этой проблемой :smirk:

**Comment by evgreb** [comment]
:+1:

**Comment by KleinenberG** [comment]
@ipelekhan , как быть тогда людям не знающим JS,ведь вы их тоже любезно приглишаете, упоминая что главное не забыть ноутбук, а дальше разбарамся, поможем. А ведь таких людей будет много и все будут дергать на себя менторв с примитивными вопросами. Или все таки предусмотрены объясниения каких-то основ необходимых для выполнения заданий?

**Comment by marinintim** [comment]
@KleinenberG:
Во-первых, есть воркшоп `javascripting`, для людей, которые совсем не знают JS. Он посвящён, в том числе, «примитивным вопросам».
Во-вторых, объяснения основ предусмотрены. (:

**Comment by KleinenberG** [comment]
@marinintim 
Понял.Спасибо за Ваши сторания)

**Comment by noorh** [comment]
:+1:

**Comment by Bah-bah** [comment]
:+1:

**Comment by small-fish** [comment]
:+1:

**Comment by Meao** [comment]
:+1:

**Comment by kapod** [comment]
:+1:

**Comment by iamyahoo** [comment]
:+1: !

**Comment by AlinaPoluykova** [comment]
:+1: !

**Comment by Johnius** [comment]
:+1:

**Comment by eugenekostylev** [comment]
:+1: (кажется, успел)

**Comment by ploninaaa** [comment]
:+1:

**Comment by blolg** [comment]
:+1:

**Comment by DmitriiTopornin** [comment]
:+1:

**Comment by Mcvriez** [comment]
+1

**Comment by Mcvriez** [comment]
:+1:

**Comment by sol-nikita** [comment]
:+1:

**Comment by luxeon89** [comment]
:+1: оставлю, на всякий случай, вдруг кто удалится:)

**Comment by marinintim** [comment]
**UPDATE 2**

Дорогие участники, мы закрываем регистрацию на этот урок, нас мнооого! :)

Если так сложилось, что вы не успели записаться на занятие до этого апдейта, не расстраивайтесь: мы повторим его, если наберется 10+ человек! Анонс будет в социальных сетях.

Но в первую очередь, анонс будет тут. Чтобы не пропустить его, мы рекомендуем подписаться на изменения репозитория в верхней части страницы.


![2015-09-19-214946_427x309_scrot](https://cloud.githubusercontent.com/assets/66025/9977675/6bf491b4-5f18-11e5-9365-4d0e893aea13.png)

**Comment by YanLobat** [comment]
так а где собсно будет мероприятие?
у эпиков не поместимся все:)

**Comment by needforjamaica** [comment]
:+1:

**Comment by loskutNat** [comment]
:+1:

**Comment by lapik86** [comment]
:+1:

**Comment by glukki** [comment]
@YanLobat ещё чуть-чуть, это сюрприз :3

**Comment by Gurylev** [comment]
:+1:
На это мероприятие я не смогу прийти, а вот на повторное пришёл бы с радостью.

**Comment by YanLobat** [comment]
Осталось меньше полутора асов, может скажете место?(

**Comment by Gurylev** [comment]
@YanLobat Мероприятие 27 сентября — ещё целая неделя.

**Comment by YanLobat** [comment]
Тьфу блин)
Не заметил)

**Comment by romankazakov** [comment]
:+1: Мест конечно уже нет,но может кто-то отвалиться до начала.

**Comment by glukki** [comment]
**UPDATE 3**

Дорогие участники, этот урок пройдет в Яндексе!

Чтобы предоставить охране БЦ список участников, мы сделали анкету. А заодно добавили туда вопросы, чтобы лучше познакомиться с вами и подготовиться к уроку.
К заполнению приглашаются те, кто зарегистрировался (:+1:) до [**UPDATE 2**](https://github.com/nodeschool/spb/issues/14#issuecomment-141697245).

Пожалуйста, заполните анкету до пятницы: http://goo.gl/forms/Js8BSXCn6K

На кофебрейке для вас будут чай, кофе и печеньки. В холле есть вендинговый автомат со снеками. На первом этаже работает японский ресторан. А можно взять с собой шоколадку или пару бутеров :)

Адрес: БЦ Бенуа, Пискарёвский пр., 2, к. 2
Как добраться: https://goo.gl/LSiS3w
Внутри: 5 этаж, Яндекс

А еще у нас есть группа ВК, в которую можно вступать: https://vk.com/nodeschool_spb :)

**Comment by byzok** [comment]
+1

**Comment by IlyakorMostovoy** [comment]
:+1:

**Comment by IlyakorMostovoy** [comment]
:+1:

**Comment by natavts** [comment]
:+1:

**Comment by glukki** [comment]
**UPDATE 4**

Итак, регистрация закрыта, список передан на охрану БЦ.
Нам очень жаль, но охрана пропустит только тех, кто внёс себя в этот список.

Если вы не успели записаться, приходите на следующий урок, предварительная запись [здесь](https://github.com/nodeschool/spb/issues/19).
Подписаться на новости можно [здесь](https://github.com/nodeschool/spb/issues/14#issuecomment-141697245) (чтобы получать письма в почту), в [ВК](https://vk.com/nodeschool_spb) или [твиттере](https://twitter.com/nodeschoolspb).

Напоминаем, что урок пройдет в Яндексе (адрес в начале страницы).
Приходить можно после 13:30, начало урока в 14:00.
Возьмите паспорт или права, чтобы пройти охрану БЦ.
И заведите аккаунт в [Телеграме](https://telegram.org).

Кто успел заполнить анкету и попасть в список для охраны (в алфавитном порядке):
@aalexeev239
@aglalit
@agufranov
@amel-true
@AnnaMukhina
@arcticmanic
@arthique
@AZ0G
@Bah-bah
@bayguzin
@Ca4tkin
@catangens
@chakzefir
@core01
@danilapisarev
@dmglazunov
@DmitriiTopornin
@eliseealex
@empas
@enjidevelop
@enkil
@eteries
@etki
@etokareva
@eugenekostylev
@evakerrigan
@evgreb
@francheskodelakoni
@Gaserd
@iamyahoo
@ierhyna
@ishaba
@kapod
@KleinenberG
@lapik86
@lunarlynx
@MaceEsina
@margolin96
@marsoupilamie
@Meao
@MhMadHamster
@midler

**Comment by glukki** [comment]
Продолжение списка:
@nastja-igel
@natavts
@needforjamaica
@nikita87200
@noorh 
@Oleg-docent
@permidon
@ploninaaa
@Realetive
@spacehaz
@tachisis
@temamix
@Tuscen
@vganshin
@voebro
@volvap
@whois42
@zolotyh

**Comment by marinintim** [comment]
Спасибо всем, что пришли! Надеюсь, вы вынесли много новой информации, а главное — поняли, где её примерно искать :)

Будет круто, если вы оставите [обратную связь](http://goo.gl/forms/5U7huzJzNI) — мы сможем понять, что можно сделать лучше.

Подписывайтесь на нас на Гитхабе, [в ВК](https://vk.com/nodeschool_spb), [в Твиттере](https://twitter.com/nodeschoolspb) и [в Телеграме](https://telegram.me/nodeschoolspb), чтобы точно узнать о новых мероприятиях. Появившиеся вопросы можно задавать в телеграмном чатике или создав ишью на Гитхабе.

А ещё я открою обратно эту ишью — если вы хотите выразить своё :+1:/:-1: этому мероприятию прямо тут.

**Comment by marinintim** [comment]
Спасибо ещё раз всем, кто пришёл, проходил воркшопы и не сдавался :)

Мы (наконец-то) выложили фотографии @h4 с мероприятия в ВК, https://vk.com/album-95068629_221840980
