### ISSUE TITLE
Повтор урока с телеграм-ботами

### ISSUE THREAD

**Issue by glukki** [nodeschool/spb#19]
Повтор урока пройдет в воскресенье.
Точную дату мы пока не можем назвать.

Чтобы предварительно записаться, оставьте комментарий с текстом `:octocat:` (он превратится в эмоджи :octocat:).

Это нужно для того, чтобы заранее оценить количество участников и лучше все спланировать :)

**Comment by luxeon89** [comment]
:octocat:

**Comment by marinintim** [comment]
:octocat:

**Comment by IlyakorMostovoy** [comment]
:octocat:

**Comment by glukki** [comment]
:octocat:

**Comment by byzok** [comment]
:octocat:

**Comment by mlogachev** [comment]
:octocat:

**Comment by odinsy** [comment]
:octocat:

**Comment by aalexeev239** [comment]
:octocat:

**Comment by sargonpiraev** [comment]
:octocat::

**Comment by AlinaPoluykova** [comment]
:octocat:

**Comment by DmitriiTopornin** [comment]
:octocat:

**Comment by loskutNat** [comment]
:octocat:

**Comment by denniselite** [comment]
:octocat:

**Comment by MarcellineTT** [comment]
:octocat:

**Comment by Nvisual** [comment]
:octocat:

**Comment by UeberSlowpoke** [comment]
:octocat:

**Comment by etokareva** [comment]
:octocat:

**Comment by KleinenberG** [comment]
:octocat:

**Comment by lapik86** [comment]
:octocat:

**Comment by ierhyna** [comment]
:octocat:
Я не смогла попасть на прошлый урок из-за непредвиденных причин, возникших в самый последний момент :( Но очень хочется пойти.

**Comment by ennett50** [comment]
:octocat:

**Comment by eugenekostylev** [comment]
:octocat:

**Comment by dmitrylebedev** [comment]
:octocat:

**Comment by Margolin96** [comment]
:octocat: (но если будет свободное место ибо я уже был :)

**Comment by CoooLLer** [comment]
:octocat:

**Comment by Johnius** [comment]
:octocat:

**Comment by dmitrylebedev** [comment]
octocat

**Comment by aalexeev239** [comment]
:octocat:

**Comment by sargonpiraev** [comment]
когда будет то?

**Comment by MarcellineTT** [comment]
:octocat:

**Comment by Johnius** [comment]
пока undefined

**Comment by russiansoon** [comment]
:octocat:

**Comment by YanLobat** [comment]
:octocat:

**Comment by aalexeev239** [comment]
:octocat:

**Comment by glukki** [comment]
:octocat:

**Comment by JasonRammoray** [comment]
:octocat:

**Comment by ipelekhan** [comment]
:octopus:

**Comment by YanLobat** [comment]
@ipelekhan так и когда урок будет?:)

**Comment by OlBol** [comment]
:octocat:

**Comment by dmitrylebedev** [comment]
:octocat: очень хочу урок

**Comment by OlBol** [comment]
https://assets-cdn.github.com/images/icons/emoji/octocat.png

**Comment by dojdev** [comment]
:octocat:

**Comment by glukki** [comment]
У нас есть точная дата!
Суббота, 13 февраля, если вы с нами — приходите на [перепись](https://github.com/nodeschool/spb/issues/21)! :)
