### ISSUE TITLE
13 февраля 2016 — основы, телеграм-боты

### ISSUE THREAD

**Issue by glukki** [nodeschool/spb#21]
Ура, повтор урока по телеграм-ботам и основам node.js состоится!  

**Когда**
День: 13 февраля, суббота.
Начало урока: 14:00; приходите к 13:40, чтобы занять место с печеньками.
Продолжительность: 6 часов с перерывами.
Место: Epic Skills, [Чкаловский пр., 15](https://goo.gl/omguzC), вход с Ораниенбаумской.
Вместимость: 30 человек.
Менторы: @marinintim, @glukki, @agufranov 

**Программа**
На уроках [`nodeschool`](http://nodeschool.io/) участники выполняют практические задания по программированию под руководством менторов.
В этот раз мы начнём с уроков [`javascripting`](http://nodeschool.io/#javascripting) и [`learnyounode`](http://nodeschool.io/#learnyounode). После этого мы перейдем непосредственно к написанию телеграм-ботов — вы можете прийти со своей идеей или выбрать одну из предложенных на уроке.
Обычно занятие идёт пять часов, поэтому у нас будут печеньки и кофе, также можно будет сходить пообедать.

**Подготовка**
Запишитесь на урок: оставьте комментарий с текстом `:octocat:` (он превратится в эмоджи :octocat:).
Поскольку все задания практические, возьмите с собой ноутбук.
Заранее установите на него необходимый набор инструментов:
- [node.js](https://nodejs.org/) версии 5;
- текстовый редактор, например [Atom](http://www.atom.io/), [Sublime Text](http://www.sublimetext.com/3), [Textmate](http://macromates.com/download), [Brackets](http://brackets.io/);
- если у вас Windows — удобный терминал, например [ConEmu](https://conemu.github.io/).

Записывайтесь и до встречи!

**Comment by aalexeev239** [comment]
:octocat:

**Comment by dmitrylebedev** [comment]
:octocat:

**Comment by russiansoon** [comment]
:octocat:

**Comment by mostalt** [comment]
:octocat:

**Comment by ipelekhan** [comment]
:octocat:

**Comment by marinintim** [comment]
:octocat:

**Comment by smirina** [comment]
:octocat:

**Comment by ierhyna** [comment]
:octocat:

**Comment by JasonRammoray** [comment]
:octocat:

**Comment by AlexeyBerezutsky** [comment]
:octocat:

**Comment by loskutNat** [comment]
:octocat:

**Comment by Cirych** [comment]
:octocat:

**Comment by Matthew-Risedale** [comment]
:octocat:

**Comment by OlBol** [comment]
:octocat:

**Comment by Reaverart** [comment]
:octocat:

**Comment by agufranov** [comment]
:octocat:

**Comment by ggfloq3** [comment]
:octocat:

**Comment by Rivestone** [comment]
:octocat:

**Comment by IlyakorMostovoy** [comment]
:octocat:

**Comment by SoftAlex** [comment]
:octocat:

**Comment by YanLobat** [comment]
:octocat:

**Comment by dojdev** [comment]
:octocat:

**Comment by plonina** [comment]
:octocat:

**Comment by stillst** [comment]
:octocat:

**Comment by fooontic** [comment]
:octocat:

**Comment by mlogachev** [comment]
:octocat:

**Comment by Smitevils** [comment]
:octocat:

**Comment by Grinv** [comment]
:octocat:

**Comment by Iamthelaw** [comment]
:octocat:

**Comment by Lushii** [comment]
:octocat:

**Comment by marinintim** [comment]
Спасибо всем ещё раз, что пришли!

Заполните, пожалуйста, [форму фидбека](http://goo.gl/forms/PUhfo1HXnS) — так мы сможем понять, что нужно сделать лучше.

Я закрываю эту ишью, если остались какие-то вопросы, то их можно задать в форме фидбека или лично [мне](https://telegram.me/marinintim) или другим организаторам.
