### ISSUE TITLE
Перевод javascripting

### ISSUE THREAD

**Issue by ipelekhan** [nodeschool/spb#22]
Перенос обсуждения из #11 

@alnero
- [x] function-arguments
- [x] function-return-values
- [x] functions
- [x] if-statement
- [x] introduction
- [x] looping-through-arrays
- [x] numbers
- [x] number-to-string
- [x] object-keys
- [x] object-properties
- [x] objects

@ipelekhan
- [x] accessing-array-values
- [x] array-filtering
- [x] arrays
- [x] for-loop
- [x] revising-strings
- [x] rounding-numbers
- [x] scope
- [x] string-length
- [x] strings
- [x] this
- [x] variables

**Comment by dmitrylebedev** [comment]
@ipelekhan, @alnero, ещё помощь не нужна?

**Comment by ipelekhan** [comment]
@dmitrylebedev, сейчас тасков не осталось, но я думаю мы будем ещё что-то переводить. А, ну и этот перевод как закончим, нужно будет вычитать и, возможно, отредактировать. Можешь за'watch'ить этот репозиторий, чтобы быть в курсе новых обсуждений.

**Comment by alnero** [comment]
Есть идеи как перевести "PIZZA OBJECT IS A GO." У меня пока:
- ОБЪЕКТ ПИЦЦА ЭТО УСПЕШНЫЙ ХОД
- ОБЪЕКТ ПИЦЦА ЭТО ШАГ ВПЕРЕД

**Comment by ipelekhan** [comment]
@alnero, на самом деле не обязательно переводить дословно, можно подобрать что-то близкое по смыслу. Так-то я тоже не знаю, что сюда можно вписать, в данном случае по сути "is a go" типа как идиома, означающая, что нечто "прошло проверку". Думаю что-то вроде "ОБЪЕКТ ПИЦЦА УДАЛСЯ!" will be just fine :smirk:

**Comment by alnero** [comment]
Это хороший перевод. Я доделал остальные упражнения.

**Comment by ipelekhan** [comment]
@alnero, отличная работа, спасибо! Я сейчас доделаю свою часть и сегодня сделаю PR в upstream.

**Comment by ipelekhan** [comment]
Done: https://github.com/sethvincent/javascripting/pull/160

**Comment by ipelekhan** [comment]
Всем спасибо за помощь :smirk:
