### ISSUE TITLE
Нодскул 23 апреля, Чкаловский, 15

### ISSUE THREAD

**Issue by marinintim** [nodeschool/spb#23]
Привет, тут очередной нодскул :)

Это уже обычный нодскул, то есть, не про телеграмных ботов (но если будете писать, всё равно поможем) -- будем изучать ноду и проходить уроки. В основном, будем проходить `learnyounode` (он для тех, кто знает js), и `javascripting` (для тех, кто ещё только начинает изучение джаваскрипта). Конечно, как и всегда, можно выбрать любой урок по вкусу, вплоть до посвященного сишной библиотеке `libuv`.

Ещё в этот раз мы несколько изменим сам формат проведения, надеюсь, будет клёво. *(Интрига)*

Время: **23 апреля (суббота)**, два часа дня;
Место: Epic Skills, *Чкаловский проспект, 15*, пятый этаж.
Менторы: @marinintim, @glukki

С собой необходимо принести **ноутбук**, ещё можно принести печенек к чаю/кофе. Если у вас уже стоит нода -- замечательно, если нет -- можете поставить самостоятельно дома или уже во время нодскула.

(любителям винды: воркшопы под Windows лучше всего работают на пятой версии ноды, если что -- обновитесь. Пора уже)

Отметьтесь в комментариях эмоджи :octocat: (пишется `:octocat:`), если собираетесь прийти.

**Comment by marinintim** [comment]
:octocat:

**Comment by ipelekhan** [comment]
:octocat:

**Comment by AntonKoshkin** [comment]
:octocat:

**Comment by AlekseyBabukh** [comment]
:octocat:

**Comment by Cirych** [comment]
:octocat:

**Comment by Gurylev** [comment]
:octocat:

**Comment by GuminEgor** [comment]
:octocat:

**Comment by alnero** [comment]
:octocat:

**Comment by astunov** [comment]
:octocat:

**Comment by perfilyev** [comment]
:octocat:

**Comment by ierhyna** [comment]
:octocat:

**Comment by loskutNat** [comment]
:octocat:

**Comment by olegk101** [comment]
:octocat:

**Comment by Iamthelaw** [comment]
:octocat:

**Comment by MaceEsina** [comment]
:octocat:

**Comment by Grinv** [comment]
:octocat:

**Comment by evgenypoyarkov** [comment]
:octocat: 

и @AVVS 
Можем помочь как менторы - организовывали [nodeschool/moscow](https://github.com/nodeschool/moscow)

**Comment by Gaserd** [comment]
:octocat:

**Comment by ipelekhan** [comment]
@evgenypoyarkov, помощи всегда рады! :smile_cat:

**Comment by freemiumhead** [comment]
:octocat:

**Comment by Smitevils** [comment]
:octocat:

**Comment by BDM30** [comment]
:octocat:

**Comment by bmsdave** [comment]
:octocat:

**Comment by glukki** [comment]
:octocat:

**Comment by marinintim** [comment]
Через пятнадцать минут начинаем! :)
