### ISSUE TITLE
27 августа; Чкаловский, 15

### ISSUE THREAD

**Issue by ipelekhan** [nodeschool/spb#29]
Привет всем! 🦄🌈

 До конца лета остаётся совсем немного и мы проводим ~~последний~~ крайний в этом сезоне нодскул! 
Нодскул — это [серия уроков](http://nodeschool.io) для самостоятельного изучения. Но если что-то не будет получаться или появится желание поговорить за JavaScript, всегда можно задать свои вопросы менторам. Уроки варьируются от базового введения в JavaScript ☕️ и Node.js 🍏, до веб-фреймворков типа Hapi ⛑, работы с react.js ⚛ и создания десктопных приложений на Electron⚡️. Обычно мероприятие длится четыре часа, но всегда можно прийти чуть позже или уйти пораньше. Вход свободный ~~как Linux~~, но лучше оставить ```:octocat:``` :octocat: в комментариях ниже, так нам проще представлять, сколько человек придёт. С собой обязательно нужно взять ноутбук 💻, а также можно захватить печеньки~~, кексы, торты, баранину в нежном соусе или некрупных омаров, отваренных на пару 🦀~~!

Дата и время: 27 августа, 16:00. Это последняя суббота августа 😋 
Менторы: @marinintim, @ipelekhan, @gurylev, @vkfont, @agufranov 
 Продолжительность: **около четырёх часов** (*и ещё афтерпати!*  🎉)
  Место: Чкаловский проспект, 15, школа интернет-технологий [Epic Skills](http://epixx.ru), пятый этаж, аудитория №2.
До занятия можно поставить [Node.js](http://nodejs.org) самостоятельно, или же можно сделать это на самом занятии, а мы, если что, поможем.
На этот раз занятия будут свободными ~~как касса~~, без особой тематики.
Приходите! 👣

**Comment by marinintim** [comment]
:octocat: :octopus: :ocean:

**Comment by ipelekhan** [comment]
:octocat:

**Comment by etki** [comment]
27 августа - суббота, разве нет?

**Comment by Gurylev** [comment]
@etki исправили

**Comment by Gurylev** [comment]
:octocat:

**Comment by MadMed677** [comment]
:octocat:

**Comment by yurvin** [comment]
:octocat:

**Comment by BelkinaDasha** [comment]
:octocat:

**Comment by dojdev** [comment]
🐙

**Comment by beardsleysmind** [comment]
:octocat: (◕‿◕✿)

**Comment by vUdav** [comment]
:octocat:

**Comment by YanLobat** [comment]
:octocat:

**Comment by devope** [comment]
иду!

**Comment by ipelekhan** [comment]
@devope, ставь```:octocat:```, это традиция 😉

**Comment by aalexeev239** [comment]
:octocat: 
![finn](http://aalexeev.ru/work/_/finn.gif)

**Comment by agufranov** [comment]
Посоны, я тоже иду!

**Comment by ishelganov** [comment]
:octocat:

**Comment by Rigwarl** [comment]
:octocat:

**Comment by ipelekhan** [comment]
Спасибо всем, кто пришёл!

**Comment by ipelekhan** [comment]
Спасибо всем, кто пришёл!
