### ISSUE TITLE
25 сентября; Чкаловский, 15

### ISSUE THREAD

**Issue by Gurylev** [nodeschool/spb#30]
Всем привет!

Осень нас уже настигла, но мы всё равно проведём сентябрьский нодскул!

Нодскул — это [серия уроков](http://nodeschool.io/) для самостоятельного изучения. Мы проводим это в формате оффлайн-занятия, чтобы вы могли задать вопросы по коду уроков менторам, а также обсудить с нами новые веяния JavaScript и Node.js.

Есть уроки и для изучения азов JavaScript и для изучения тонкостей библиотек Node.js. Если возникнут проблемы, мы поможем
* запилить сайт на Express, Hapi или Koa
* разобраться, как и где хранить данные для ваших приложений
* упростить жизнь библиотеками
* разобраться, как отлаживать ваш код
* написать первые тесты
* изучить азы реакта
* и даже поможем написать десктопное приложение на Electron, если вы до этого доберётесь. 

Или вы справитесь без нашей помощи ;-)

Обычно мероприятие длится четыре часа, но всегда можно прийти чуть позже или уйти пораньше. Вход свободный, но лучше оставить `:octocat:` :octocat: в комментариях ниже и написать, [какой воркшоп](http://nodeschool.io/) вы будете изучать. Зная количество человек и изучаемые воркшопы мы сможем лучше подготовиться. С собой обязательно нужно взять ноутбук, а ещё можете захватить печеньки или другие вкусняшки.  

**Дата и время**: 25 сентября, 16:00.
**Менторы**: @marinintim, @ipelekhan, @gurylev, @vkfont, @agufranov 
 **Продолжительность**: около четырёх часов (и ещё афтерпати! 🎉)
  **Место**: Чкаловский проспект, 15, школа интернет-технологий [Epic Skills](http://epixx.ru/), пятый этаж, аудитория №2. После лестницы налево и до конца по коридору. 

До занятия желательно установить [Node.js](https://nodejs.org/) и [Git Bash](https://git-scm.com/) самостоятельно, или же можно сделать это на самом занятии, а мы, если что, поможем.
На этот раз занятия будут свободными, без особой тематики.
Приходите!

**Comment by ipelekhan** [comment]
⭕ 🅾️ 🌊 :octocat: 🐙

**Comment by marinintim** [comment]
:octocat:

Буду проходить `torrential` и `going-native`!

**Comment by vUdav** [comment]
:octocat:

**Comment by underoot** [comment]
:octocat:

**Comment by diagnosefiz** [comment]
:octocat: тоже хочу прийти попробовать 'learnyounode'

**Comment by safinalexey** [comment]
:octocat:

**Comment by etki** [comment]
stream-adventure :octocat:

**Comment by vforvova** [comment]
:octocat: stream-adventure

**Comment by romankazakov** [comment]
:octocat:

**Comment by Alinamur** [comment]
:octocat: хочу пройти learnyounode

**Comment by onmoon** [comment]
:octocat: react

**Comment by beardsleysmind** [comment]
:octocat: lrnynd

**Comment by Rigwarl** [comment]
:octocat: learnyounode

**Comment by yurvin** [comment]
Хочу пройти webgl-workshop

**Comment by pavlov-tony** [comment]
:octocat: stream-adventure

**Comment by web2ls** [comment]
:octocat:

**Comment by JuliaPhoenix** [comment]
:octocat:  javascripting,learnyounode

**Comment by zimenskiy** [comment]
:octocat: `stream-adventure` или `elementary-electron`

**Comment by Matthew-Risedale** [comment]
:octocat:

**Comment by Satiata** [comment]
:octocat: `javascripting`

**Comment by eveness** [comment]
:octocat:  `learnyounode` `stream-adventure`

**Comment by ennett50** [comment]
:octocat: javascripting scope-chains-closures count-to-6

**Comment by pashaandsik** [comment]
:octocat: "javascripting" "scope-chains-closures"

**Comment by waldyslaw** [comment]
:octocat:

**Comment by smirina** [comment]
:octocat: learnyounode learnyoureact

**Comment by vshurupov** [comment]
:octocat:

**Comment by mostalt** [comment]
:octocat: learnyounode

**Comment by bartlex** [comment]
:octocat: stream-adventure learn-generators kick-off-koa

**Comment by Annushka1** [comment]
:octocat:

**Comment by alnero** [comment]
:octocat: *`stream-adventure`*

**Comment by arthique** [comment]
:octocat: learnyounode

**Comment by MistaTwista** [comment]
:octocat:

**Comment by halofourteen** [comment]
:octocat: `kick-off-koa`

**Comment by a-omarova** [comment]
:octocat:

**Comment by boykovdmitriy** [comment]
:octocat: learnyounode

**Comment by n1xxx0n** [comment]
:octocat:

**Comment by jaarenov** [comment]
:octocat: javascripting  learnyounode

**Comment by nomi2213** [comment]
:octocat: javascripting

**Comment by Aerena** [comment]
:octocat: `javascripting`

**Comment by DmitryTa** [comment]
:octocat:

**Comment by andpav** [comment]
![image](https://cloud.githubusercontent.com/assets/17623743/18811007/668d9568-82ad-11e6-814d-b10570be70d7.png)  learnyounode

**Comment by andpav** [comment]
:octocat: learnyounode

**Comment by Meao** [comment]
:octocat:

**Comment by Gurylev** [comment]
Огромное спасибо всем, что пришли!
В итоге было 25 человек из обещанных 42. Вы крутые! [Фоточки тут](https://vk.com/album-95068629_236532071).

[Расскажите](https://goo.gl/forms/bazCD0CHr7FbA4Is1), что вам понравилось, а что хорошо бы поменять. Хочется понимать, как мероприятие оцениваете вы, что желаете поменять, а за что хотите похвалить.
