### ISSUE TITLE
22 октября; Wrike (Свердловская набережная, 44д) 

### ISSUE THREAD

**Issue by marinintim** [nodeschool/spb#35]
Привет!

22 октября мы проведём одиннадцатый нодскул. В этот раз у нас **новое место** &mdash; офис компании Wrike! 

<a href="https://yandex.ru/maps/-/CZgijJ2E" target="_blank" style="display: block; float: left;"><img src="https://cloud.githubusercontent.com/assets/66025/19266449/3b6be972-8fb2-11e6-8511-5b41d1d107e3.png"></a>

:world_map: Карта кликабельна и ведёт на Яндекс.Карты.

👣 от остановки пл. Ленина д.1 ходят автобусы 106, 133 и 37. Доехать нужно до остановки ул. Феодосийская и далее [немного пешком](http://grlv.ru/i/weekend-bus-to-wrike.png). Бесплатные автобусы от БЦ Полюстрово по выходным не ходят, не ждите их!

:classical_building: Адрес БЦ: Свердловская набережная, 44д, вход [справа](http://grlv.ru/i/wrike-photo-entry.png). *[а давайте вместе поедем, а?]*

:clock4: 22 октября &mdash; это суббота. Мы начнём в **16:00**.

В этот раз менторят @marinintim, @Gurylev, @ipelekhan :tada: 

**Внимание**: так как офис находится в БЦ &laquo;Лето&raquo;, нам нужно собрать список для охраны. Заполните, пожалуйста, форму (регистрация уже закрыта). И приходите ОБЯЗАТЕЛЬНО с паспортом! На входе охрана будет проверять по спискам зарегистрированных.

Чтобы прийти, нужно отметиться в форме и, конечно, взять с собой ноутбук :computer:!

=========

Нодскул &mdash; это формат самостоятельного обучения, где участники проходят воркшопы (наборы заданий с автоматическими проверками). Список воркшопов можно посмотреть на [nodeschool.io](http://nodeschool.io), есть самые разнообразные темы :book:  обычно мероприятие длится около четырёх часов, но всегда можно уйти пораньше.

На каждом нодскуле есть менторы, которые помогают в трудных ситуациях. Иногда достаточно взгляда другого человека, чтобы увидеть ошибку самому. :smirk: 

Вам понадобится ноутбук, если хотите &mdash; можно заранее установить [Node.js](https://nodejs.org), но если что &mdash; поможем установить на мероприятии :incoming_envelope: 

=========

Вопросы можно задавать прямо тут!

🖖 Пожалуйста, пишите названия воркшопов, которые планируете проходить!
Это поможет нам лучше подготовиться к ответам на вопросы.

:no_bell: Если вас смущают письма про новые комментарии к ишье, то справа можно отписаться от уведомлений.

:shipit: До встречи! :anchor:

**Comment by marinintim** [comment]
:octocat:

**Comment by a-omarova** [comment]
:octocat:

**Comment by eveness** [comment]
:octocat:

**Comment by d4rkm3z** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/octocat.png)

**Comment by d4rkm3z** [comment]
:octocat:

**Comment by aprocom** [comment]
:octocat:

**Comment by natasha-multsina** [comment]
:octocat:

**Comment by AntonKoshkin** [comment]
:octocat:

**Comment by MadMed677** [comment]
:octocat:

**Comment by etki** [comment]
:shipit:

**Comment by Gurylev** [comment]
Пожалуйста, пишите названия воркшопов, которые планируете проходить!
Это поможет нам лучше подготовиться к ответам на вопросы.

**Comment by safinalexey** [comment]
:octocat:

**Comment by mostalt** [comment]
:octocat:

**Comment by shvgn** [comment]
:octocat:

**Comment by vkhv** [comment]
:octocat:

**Comment by Alinamur** [comment]
:octocat: learnyounode

**Comment by Graver75** [comment]
:octocat: tower-of-babel

**Comment by web2ls** [comment]
:octocat:  Thinking in React

**Comment by juugarkina** [comment]
:octocat: learnyounode

**Comment by vganshin** [comment]
:octocat:

**Comment by 3enkal** [comment]
:octocat: список интересных воркшопов описала в формочке

**Comment by dojdev** [comment]
:octocat: надеюсь добить learnyounode

**Comment by Annushka1** [comment]
:octocat: буду опоздуном

**Comment by thedoctorde** [comment]
:octocat:

**Comment by Nors2064** [comment]
:octocat:

**Comment by chakzefir** [comment]
+

**Comment by lancelote** [comment]
:octocat: javascripting, git-it, how-to-markdown

**Comment by ipelekhan** [comment]
:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat:

**Comment by jaarenov** [comment]
:octocat: learnyounode

**Comment by DmitryTa** [comment]
:octocat: learnyounode

**Comment by plonina** [comment]
:octocat:

**Comment by ipelekhan** [comment]
[:octocat:](http://codepen.io/ipelekhan/pen/rrAmEo)

**Comment by elemeNtk0** [comment]
:octocat:

**Comment by romanburtnek** [comment]
:octocat: javascripting

**Comment by ilyapasyuk** [comment]
javascripting, learnyounode

**Comment by Matthew-Risedale** [comment]
:octocat:

**Comment by shaveko** [comment]
test-anything, learnyoureact

**Comment by Chikiro** [comment]
:octocat: learnyounode, scope-chains-closures, learnyoureact

**Comment by Gurylev** [comment]
:octocat: elementary-electron

**Comment by Gurylev** [comment]
Регистрация закроется утром в пятницу. Списки нужно ещё передать охране. Успейте ;-)

**Comment by Meao** [comment]
learnyounode

**Comment by matthewstifler** [comment]
:octocat:

**Comment by isqua** [comment]
:octocat:

**Comment by Gurylev** [comment]
Регистрация закрыта! Сегодня списки будут переданы охране БЦ Лето. При входе не забудьте паспорта или права, чтобы вам выдали временные пропуска.

Если кто-то не успел или забыл заполнить форму - к сожалению, вас не пропустят на входе. Приходите на следующие встречи! О них мы расскажем здесь [на гитхабе](https://github.com/nodeschool/spb/issues?q=is%3Aissue+is%3Aopen+label%3A%D0%9C%D0%B5%D1%80%D0%BE%D0%BF%D1%80%D0%B8%D1%8F%D1%82%D0%B8%D0%B5), в [группе вк](https://vk.com/nodeschool_spb), [телеграме](https://telegram.me/nodeschoolspb_group) и [твиттере](https://twitter.com/nodeschoolspb).

Напоминаем, что урок пройдет в Wrike (адрес в начале страницы).
Приходить можно после 15:30, начало урока в 16:00.

Кто успел заполнить форму и попасть в список для охраны (в алфавитном порядке).
@3enkal
@a-omarova
@afoninsky
@Alinamur
@Annushka1
@AntonKoshkin
@aprocom
@aqus
@bokcart
@Caso05
@chikiro
@DmitryTa
@dojdev
@elemeNtk0
@etki
@eveness
@Graver75
@Gurylev
@iamyahoo
@ilyapasyuk
@ipelekhan
@isqua
@jaarenov
@justGoodFellow
@juugarkina
@lancelote
@madmed677
@marinintim
@matthewstifler
@misterblblbl
@mostalt
@n1xxx0n
@natasha-multsina
@Nors2064
@OlBol
@Olegk101
@pret-a-porter
@romanburtnek
@safinalexey
@shaveko
@shvgn
@sidderman324
@thedoctorde
@useacode
@vkhv

**Comment by 3enkal** [comment]
раньше вроде бы не было 16:00 или я не внимательно читала?((( Я почему-то ориентировалась на первую половину дня( к сожалению, в 16 поздновато 
Вношу предложение проводить следующие уроки по-раньше))

**Comment by Gurylev** [comment]
@3enkal было сразу в 16:00. Раньше бывало в 14:00 в epic skills. В пршлый раз тоже было в 16:00. Так складываются обстоятельства 😢 
Мы постараемся делать впредь в 14:00. Спасибо, что поделилась этой проблемой, мы обязательно учтём.

**Comment by Gurylev** [comment]
Спасибо, что пришли! Было 23 человека из обещанных 47. Вы были бомбически круты!

[Оставьте конструктивный отзыв](https://vk.com/wall-129100640_8)
Желательно и похвалить и поругать, чтоб мы знали, что улучшать.

[Посмотрите фоточки](https://vk.com/album-95068629_237397450)
