### ISSUE TITLE
19 ноября 2016 года; Чкаловский, 15

### ISSUE THREAD

**Issue by Gurylev** [nodeschool/spb#41]
Всем привет!

Зима подкралась незаметно, раньше ожидаемого - снег всюду. А у нас на носу ноябрьский нодскул.

**Нодскул** — это ежемесячные оффлайн-встречи, где участники проходят [уроки](https://nodeschool.io/#workshoppers) с авто-проверками и задают возникшие вопросы по коду уроков опытным кодерам. А ещё это отличное место для обсуждения новостей из мира JavaScript и Node.js.

Уроки помогают изучить JavaScript от азов до сложных тонкостей библиотек Node.js.
Мы поможем понять
* как запилить сайт на Express, Hapi или Koa
* как и где хранить данные для ваших приложений
* как упростить жизнь библиотеками
* как отлаживать ваш код
* как написать первые тесты
* как изучить азы реакта
* и даже поможем написать десктопное приложение на Electron, если вы доберётесь.

Или вы справитесь без нашей помощи ;-)

Обычно мероприятие длится четыре часа, но всегда можно прийти чуть позже или уйти пораньше. Вход свободный, но лучше оставить `:octocat:`:octocat: в комментариях ниже и написать, [какой воркшоп](https://nodeschool.io/#workshoppers) вы планируете изучать. Зная количество человек и изучаемые воркшопы мы сможем лучше подготовиться. С собой обязательно нужно взять ноутбук, а ещё можете захватить печеньки или другие вкусняшки.  

🕓 **Дата и время**: 19 ноября (суббота), 14:00.
⌛️ **Продолжительность**: 4 часа, закончим в 18:00 (а потом афтерпати!)
🏛 **  Место**: Чкаловский проспект, 15, школа интернет-технологий [Epic Skills](http://epixx.ru/), пятый этаж, аудитория №3. После лестницы направо, дальше по указателям.
⛑ **Менторы**: @marinintim, @ipelekhan, @gurylev, @vkfont, @agufranov, @bitgorbovsky, @eveness

До занятия желательно установить [Node.js](https://nodejs.org/) и [Git Bash](https://git-scm.com/) самостоятельно. Мы поможем сделать это на занятии, если потребуется.
На этот раз занятия будут свободными, без особой тематики. Вы вольны [выбрать](https://nodeschool.io/#workshoppers) сами.
Приходите!

**Comment by Aerena** [comment]
:octocat: learnyounode, scope-chains-closures

**Comment by yurvin** [comment]
+

**Comment by elemeNtk0** [comment]
:octocat: learnyounode, scope-chains-closures (возможно)

**Comment by safinalexey** [comment]
:octocat:

**Comment by vovakulikov** [comment]
:octocat:

**Comment by ilyapasyuk** [comment]
Scope Chains & Closures

**Comment by idmitriev** [comment]
:octocat:

**Comment by b-ponomarenko** [comment]
:octocat:

**Comment by RusPosevkin** [comment]
:octocat:

**Comment by bartlex** [comment]
:octocat:

**Comment by luxeon89** [comment]
:octocat: Basic JavaScript

**Comment by a-omarova** [comment]
:octocat:

**Comment by Matthew-Risedale** [comment]
:octocat:

**Comment by n1xxx0n** [comment]
:octocat:

**Comment by CubiZm** [comment]
:octocat:
learnyounode, Scope Chains & Closures, stream-adventure

**Comment by dojdev** [comment]
:octocat: stream-adventure или how-to-npm

**Comment by Dan-Ste** [comment]
:octocat:

**Comment by Kris-Kovach** [comment]
:octocat:

**Comment by safinalexey** [comment]
тем, кто собирается проходить stream-adventure - если вы до этого не работали со стримам, то это приключение на 6-8 часов)

**Comment by alexeyvax** [comment]
:octocat:

**Comment by ipelekhan** [comment]
:octocat:

**Comment by natasha-multsina** [comment]
:octocat:

**Comment by youngpirate32** [comment]
:octocat:

**Comment by dcromster** [comment]
:octocat:

**Comment by AntonKoshkin** [comment]
:octocat: любопытны реакт и экспресс

**Comment by a-pavlov-parc** [comment]
:octocat:

**Comment by Nesterrr** [comment]
:octocat:

**Comment by Sfolt** [comment]
:octocat:

**Comment by zacharymartin** [comment]
javascripting, git-it

**Comment by dmitrylebedev** [comment]
:octocat:

**Comment by shmulya** [comment]
:octocat:

**Comment by dmitrika** [comment]
:octocat:

**Comment by devope** [comment]
:octocat:

**Comment by pvlv** [comment]
:octocat:

**Comment by mostalt** [comment]
:octocat: learnyounode stream-adventure

**Comment by maxefi** [comment]
:octocat: 
scope-chains-closures && promise && count-to-6 && learnyoureact && thinking-in-react

YEAN NO FOR SURE

**Comment by net0** [comment]
:octocat:

**Comment by spbsmile** [comment]
:octocat: 
scope-chains-closures && promise && count-to-6 && learnyoureact && thinking-in-react

**Comment by mark-selyaeff** [comment]
:octocat: 
Functional JS and learnyoureact

**Comment by atomlex** [comment]
:octocat:

**Comment by Realetive** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/octocat.png)

**Comment by yana123456** [comment]
:octocat:

**Comment by lancelote** [comment]
:octocat:

javascripting, git-it, how-to-markdown

**Comment by binjospookie** [comment]
:octocat:

**Comment by bmsdave** [comment]
:octocat:

**Comment by olegk101** [comment]
:octocat:

**Comment by antonazgarovich** [comment]
:octocat: Scope Chains & Closures, learnyounode, stream-adventure, ExpressWorks, Functional Javascript, Level Me Up Scotty!

**Comment by matthewstifler** [comment]
:octocat:

**Comment by gucol** [comment]
:octocat:

**Comment by marinintim** [comment]
Привет! Нас записалось столько, что мы переживаем за вместимость :) 
Если вы отметились, но не придёте, то, пожалуйста, обновите или удалите свой комментарий. 
Если вы тянули до последнего и очень хотите попасть именно на этот нодскул, но не успели - напишите любому ментору на ваш выбор. 

И подписывайтесь и ставьте звёздочки, тогда увидите сообщение про новые нодскулы раньше других ;) 

До встречи на нодскуле!

**Comment by Gurylev** [comment]
Вчера было 36 человек из обещанных 50. Плюс ещё человек 10 напросились прийти после закрытия регистрации и пришли!

Спасибо всем, кто пришёл! Вы круто справлялись, молодцы! На этот раз многие проходили не только javascripting и learnyounode, но и воркшопы по экспрессу, реакту и даже GLSL. Офигенно!

Поделитесь впечатлениями в комментариях под этим постом вконтакте https://vk.com/nodeschool?w=wall-129100640_19 или напишите в телеграме
Нам очень нужны ваши отзывы!

А ещё тут фоточки подоспели
https://vk.com/album-95068629_238430384
