### ISSUE TITLE
24 декабря 2016 года; Цветочная 19 (Дата-центр Selectel)

### ISSUE THREAD

**Issue by safinalexey** [nodeschool/spb#42]
Всем привет!

На дворе почти декабрь, скоро новый год, а это значит, что нас ждёт рождественский нодскул!

**Нодскул** — это ежемесячные оффлайн-встречи, где участники проходят [уроки](https://nodeschool.io/#workshoppers) с авто-проверками и задают возникшие вопросы по коду уроков опытным кодерам. А ещё это отличное место для обсуждения новостей из мира JavaScript и Node.js.

Уроки помогают изучить JavaScript от азов до сложных тонкостей библиотек Node.js.
Мы поможем понять

- как запилить сайт на Express, Hapi или Koa
- как и где хранить данные для ваших приложений
- как упростить жизнь библиотеками
- как отлаживать ваш код
- как написать первые тесты
- как изучить азы реакта, шейдеров
- и даже поможем написать десктопное приложение на Electron, если вы доберётесь.

Или вы справитесь без нашей помощи ;-)

Обычно мероприятие длится четыре часа, но всегда можно прийти чуть позже или уйти пораньше. 

⚠️ **Внимание**
Регистрация закрыта

В форме есть вопрос про воркшоп, который вы желаете пройти. Список воркшопов доступен [по этой ссылке](https://nodeschool.io/#workshoppers). Зная количество человек и изучаемые воркшопы мы сможем лучше подготовиться к вашим вопросам. С собой обязательно нужно взять ноутбук(и установить на нём NodeJS). На месте будут кофе\чай, ништяки к нему, пицца, стикеры и мягкие подарки от Селектела.

🕓 Дата и время: 24 декабря (суббота), 14:00.
⌛️ Продолжительность: 4 часа, закончим в 18:00
🏛   Место: Цветочная улица, 19, дата-центр Selectel, вход с улицы, первый этаж. На входе вам нужно будет показать паспорт охране и отметиться в списке
⛑ Менторы: @marinintim, @safinalexey, @gurylev, @ipelekhan, @bitgorbovsky, 

<a href="https://yandex.ru/maps/-/CZDBFGyt" target="_blank"><img width="1004" alt="_ _ _ _ _ _ _" src="https://cloud.githubusercontent.com/assets/1890197/20643103/ba56c746-b430-11e6-8342-e0771b850193.png"></a>

**Comment by safinalexey** [comment]
:octocat:

**Comment by Nesterrr** [comment]
:octocat:

**Comment by dojdev** [comment]
:octocat:

**Comment by luxeon89** [comment]
:octocat:

**Comment by NMVikings** [comment]
:octocat:

**Comment by agufranov** [comment]
:octocat:

**Comment by Aerena** [comment]
:octocat:

**Comment by ilyapasyuk** [comment]
:octocat:

**Comment by shvgn** [comment]
:octocat:

**Comment by olegk101** [comment]
:octocat:

**Comment by ERazina** [comment]
:octocat:

**Comment by ipelekhan** [comment]
:octocat:

**Comment by elemeNtk0** [comment]
:octocat:

**Comment by thatsnotplasticine** [comment]
:octocat:

**Comment by alexeyvax** [comment]
:octocat:

**Comment by g1un** [comment]
:octocat:

**Comment by matthewstifler** [comment]
:octocat:

**Comment by 7flash** [comment]
:octocat:

**Comment by Prosv** [comment]
:octocat:

**Comment by rybchek** [comment]
:octocat:

**Comment by s-ilya** [comment]
:octocat:

**Comment by Matthew-Risedale** [comment]
:octocat:

**Comment by thehanseiway** [comment]
: octocat:

**Comment by thehanseiway** [comment]
:octocat:

**Comment by DmitryTa** [comment]
:octocat: stream-adventure

**Comment by cotang** [comment]
:octocat:

**Comment by beardsleysmind** [comment]
:octocat:

**Comment by b-ponomarenko** [comment]
:octocat:

**Comment by mikaspell** [comment]
:octocat:

**Comment by underoot** [comment]
:octocat: stream-adventure

**Comment by aqus** [comment]
:octocat:

**Comment by Gaserd** [comment]
:octocat:

**Comment by Cirych** [comment]
:octocat:
Async You || Kick off Koa || learnyoureact || Thinking in React || Currying in JavaScript - что-то из этого

**Comment by 3enkal** [comment]
:octocat:

**Comment by vlshat** [comment]
:octocat:

**Comment by matpaul** [comment]
:octocat:

**Comment by juugarkina** [comment]
:octocat:

**Comment by belozerskiy** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/octocat.png)

**Comment by yagee** [comment]
:octocat:

**Comment by maxefi** [comment]
:octocat:

**Comment by VladBlow** [comment]
:octocat:

**Comment by Diedrow** [comment]
:octocat:

**Comment by Ostendeek** [comment]
:octocat:

**Comment by SalinderNikolay** [comment]
:octocat:

**Comment by AntonKoshkin** [comment]
:octocat:

**Comment by anna-naumova** [comment]
:octocat:

**Comment by OlBol** [comment]
:octocat:

**Comment by yana123456** [comment]
:octocat:

**Comment by a-omarova** [comment]
:octocat:

**Comment by bartlex** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/octocat.png)

**Comment by ierhyna** [comment]
:octocat:

**Comment by FChaack** [comment]
:octocat:

**Comment by bezrukov** [comment]
:octocat:

**Comment by SGKuksov** [comment]
:octocat:

**Comment by pepelsbey** [comment]
:octocat:

**Comment by Gurylev** [comment]
**Хочу напомнить**: вы не сможете пройти в дата-центр Selectel, если охрана не найдёт вас в списке. Чтобы попасть в этот список, обязательна регистрация [в этой форме](https://goo.gl/forms/0JPYAfbzJxSYzgA62).

@7flash, @Aerena, @agufranov, @bartlex, @belozerskiy, @FChaack, @Gaserd, @ilyapasyuk, @matpaul, @matthewstifler, @Prosv , @thehanseiway, @yana123456 особенно это касается вас. Сейчас вас нет в списке заполнивших форму. Пожалуйста, заполните её. Это займёт две минуты.

**Comment by bokcart** [comment]
:octocat:

**Comment by ilnurnasyrov** [comment]
:octocat:

**Comment by smirina** [comment]
:octocat:

**Comment by Kris-Kovach** [comment]
:octocat:

**Comment by misterblblbl** [comment]
:octocat:

**Comment by sidderman324** [comment]
:octocat:

**Comment by alekseyRabiner** [comment]
Планируете ли проводить онлайн трансляции? С удовольствием посетил бы мероприятие, но географически очень далеко нахожусь.

**Comment by ilyapasyuk** [comment]
В данном формате мероприятия в этом нет смысла. Все заняты своими делами.

**Comment by Gurylev** [comment]
@alekseyRabiner как написано выше, нам нечего транслировать. Мы не выступаем с докладами. Каждый приходит с ноутбуком и решает [воркшопы](https://nodeschool.io/#workshopper-list). Это выглядит примерно [вот так](https://pp.vk.me/c604417/v604417163/3913a/FxPE7ZAnhHM.jpg).

**Comment by alekseyRabiner** [comment]
@Gurylev @ilyapasyuk спасибо за ответы.

**Comment by cinic** [comment]
:octocat:

**Comment by barabaz-z-z** [comment]
:octocat:

**Comment by nekhaevskiy** [comment]
:octocat:

**Comment by mrwebic** [comment]
:octocat:

**Comment by nsobyanin** [comment]
:octocat:

**Comment by aikrikunov95** [comment]
:octocat:

**Comment by romankazakov** [comment]
:octocat:

**Comment by zjoin** [comment]
:octocat:

**Comment by yurvin** [comment]
:octocat

**Comment by natavts** [comment]
:octocat:

**Comment by bethliss** [comment]
:octocat:

**Comment by Gurylev** [comment]
Крайний срок записи - сегодня! После мы отдадим списки посетителей охране. Записаться позже не получится. Ловите момент!

**Comment by Gurylev** [comment]
Хочу ещё раз напомнить про обязательное заполнение [формы регистрации](https://goo.gl/forms/0JPYAfbzJxSYzgA62). Вы не сможете пройти в дата-центр Selectel, если охрана не найдёт вас в списке.
@sidderman324 @yurvin @7flash @agufranov @bartlex @Gaserd @matpaul @matthewstifler @Prosv @thehanseiway @yana123456 особенно это касается вас. Сейчас вас нет в списке заполнивших форму. Сегодня последний день, когда вы можете заполнить форму.

**Comment by russiansoon** [comment]
:octocat:

**Comment by choibalsan** [comment]
:octocat:

**Comment by Rivestone** [comment]
:octocat:

**Comment by safinalexey** [comment]
Регистрация закрыта

**Comment by marinintim** [comment]
Спасибо всем, кто пришёл, и до встречи в следующем году!
