### ISSUE TITLE
28 января 2017 года; JetBrains (Университетская наб., 7-9-11 к. 5А)

### ISSUE THREAD

**Issue by Gurylev** [nodeschool/spb#47]
Всем привет!

Поздравляем с наступившим 2017 годом! Желаем вам пройти как минимум ещё 12 воркшопов в грядущем году. В январе нодскул снова на новом месте: в офисе JetBrains.

<a href="http://grlv.ru/l/nodeschool-jetbrains-map1" target="_blank" style="display: block; float: left;"><img src="http://grlv.ru/i/nodeschool-map-28.01.2017.png"></a>

Нодскул — это ежемесячные оффлайн-встречи, где участники проходят [уроки](https://nodeschool.io/#workshoppers) с авто-проверками и могут задать вопросы по коду уроков опытным кодерам. Уроки помогают изучить JavaScript от азов до сложных тонкостей библиотек Node.js.

Мы поможем понять
- как запилить сайт на Express, Hapi или Koa
- как превратить сайт в кроссплатформенное приложение на Electron
- как и где хранить данные для ваших приложений
- как упростить жизнь библиотеками
- как упростить работу со стилями при помощи sass или less
- как отлаживать ваш код
- как перейти на современный ES стандарт
- как работать с бинарными данными, графикой и аудио
- как написать первые тесты
- как изучить азы и философию ReactJS
- как разобраться в прототипном или в функциональном программировании
- и как отличить лучшие практики написания чистого JS

**[[[=== регистрация уже закрыта ===]]]**

Чтобы попасть на нодскул, вы должны заполнить форму (регистрация закрыта) и оставить `:octocat:` :octocat: здесь в комментариях. С собой обязательно нужно взять ноутбук для кодинга и паспорт/права для преодоления охраны. 

**Дата и время**: 28 января, с 14 до 18 часов (4 часа) + афтерпати!
**Менторы**: @marinintim, @gurylev, @safinalexey, @vkfont, @agufranov, @bitgorbovsky
**  Место**: Университетская наб., 7-9-11 к. 5А, офис [JetBrains](https://www.jetbrains.com/) (здание с надписью Universe).

Желательно заранее установить [Node.js](https://nodejs.org/en/download/) и [Git Bash](https://git-scm.com/downloads), но если что —  мы поможем уже на мероприятии. И ещё хорошо бы воркшоп для прохождения [выбрать](https://nodeschool.io/#workshoppers) заранее.

Приходите! И если есть вопросы - задавайте прямо тут.

**Comment by misterblblbl** [comment]
:octocat:

**Comment by Nesterrr** [comment]
:octocat:

**Comment by dojdev** [comment]
:котик:

**Comment by Aerena** [comment]
:octocat:

**Comment by Matthew-Risedale** [comment]
:octocat:

**Comment by GeorgeGorbanev** [comment]
:octocat:

**Comment by luxeon89** [comment]
:octocat:

**Comment by yurvin** [comment]
:octocat:

**Comment by IlyakorMostovoy** [comment]
:octocat:

**Comment by Dan-Ste** [comment]
:octocat:

**Comment by AntonKoshkin** [comment]
:octocat:

**Comment by mdnkspb** [comment]
:octocat:

**Comment by nekhaevskiy** [comment]
:octocat:

**Comment by matthewstifler** [comment]
:octocat:

**Comment by bmsdave** [comment]
:oktokot:

**Comment by spbsmile** [comment]
:octocat

**Comment by nagliy-pirojok** [comment]
:octocat:

**Comment by OlBol** [comment]
:octocat:

**Comment by Kealman** [comment]
:octocat:

**Comment by ilyapasyuk** [comment]
:octocat:

**Comment by safinalexey** [comment]
:octocat:

**Comment by thatsnotplasticine** [comment]
:octocat:

**Comment by VladBlow** [comment]
:octocat:

**Comment by elemeNtk0** [comment]
:octocat: `git-it`, `scope-chains-closures`

**Comment by bethliss** [comment]
:octocat:

**Comment by fasteasy** [comment]
:octocat:

**Comment by Dreug** [comment]
:octocat: :

**Comment by Jurhard** [comment]
:kot:

**Comment by alexgriss** [comment]
:octocat:

**Comment by Nvisual** [comment]
:octocat:

**Comment by Diedrow** [comment]
:octocat:

**Comment by FChaack** [comment]
:octocat:

**Comment by marinintim** [comment]
Шаблончик для гуглкалендаря: https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=cTB0M2cxcTQxMmtwMXJkcnY0dXA2MnI5Y28gbWFyaW5pbnRpbUBt&tmsrc=marinintim%40gmail.com

**Comment by bokcart** [comment]
:octocat:

**Comment by Annushka1** [comment]
:octocat:

**Comment by mostalt** [comment]
:octocat:

**Comment by SGKuksov** [comment]
:octocat:

**Comment by ennett50** [comment]
:octocat:

**Comment by DmitryTa** [comment]
:octocat:

**Comment by beardsleysmind** [comment]
:octocat:

**Comment by jaarenov** [comment]
:octocat:

**Comment by arthique** [comment]
:octocat:

**Comment by go4d1** [comment]
Я инженер-программист в Нью-Йорке. Я хотел бы принять участие в конференции или программного обеспечения класса в Санкт-Петербурге. Мои знания русского языка элементарно - но я хорошо установленный разработчиком программного обеспечения. Я был бы признателен за все, что вы можете рекомендую - Я ожидаю, что в Санкт-Петербурге в июле или августе. В прошлом я работал с разработчиками программного обеспечения, связанных с EPAM в Минске. My Linked in Bio is: https://www.linkedin.com/in/marty-glynn-48894414/  email: mg@theateronline.com - Thank you!

**Comment by AlexeyProskuryakov** [comment]
:octocat:

**Comment by ipelekhan** [comment]
@go4d1 
Hi, Martin! Could you please repeat your question in English, please? Google translated text is barely possible to understand 😄 

If I got you right, you want to participate in our event during your stay in Saint Petersburg at July or August. It's one hundred percent possible, just click on ```watch``` button in this repository and track the ```Мероприятие``` tag (which means "event" in Russian). We organize our local events each month, and publish time and place two weeks before the event.
![28_ _2017_ __jetbrains__ _ ___7-9-11_ __5 __ _issue__47_ _nodeschool_spb](https://cloud.githubusercontent.com/assets/2616427/21963660/ec777286-db57-11e6-8f44-1cddf6706baf.png)

**Comment by go4d1** [comment]
Thanks for the response. I clicked  the Watch Button and I will check the  <https://github.com/nodeschool/spb/issues?q=is%3Aopen+label%3A%D0%9C%D0%B5%D1%80%D0%BE%D0%BF%D1%80%D0%B8%D1%8F%D1%82%D0%B8%D0%B5> Мероприятие

 

I’m a retired developer but I’d like to stay active and I have many business acquaintances here in the US.

 

I’d like to attend a class or conference in St. Petersburg or Moscow if there’s one available. I’d also like to make contacts with developers who know Angular 2 and MongoDB. 

 

My prior company worked with  <https://epam.com> https://epam.com.  They outsource development to Minsk and Moscow. We were never that happy with them. 

 

I will attend this NodeSchool event in NY  <https://www.meetup.com/NY-JavaScript/events/236674883/> https://www.meetup.com/NY-JavaScript/events/236674883/

Thanks again for the response.

Действительно, мой русский не так уж плохо. В следующий раз я не буду использовать Google Translate, я сделаю это сам.

Martin

**Comment by natavts** [comment]
:octocat:

**Comment by alnero** [comment]
:octocat:

**Comment by plonina** [comment]
:octocat:

**Comment by Ostendeek** [comment]
:octocat:

**Comment by smirina** [comment]
:octocat:

**Comment by Kris-Kovach** [comment]
:octocat:

**Comment by sidderman324** [comment]
:octocat:

**Comment by vforvova** [comment]
:octocat:

**Comment by MaceEsina** [comment]
:octocat:

**Comment by shaveko** [comment]
:octocat:

**Comment by bitharmony** [comment]
<img class="emoji" title=":octocat:" alt=":octocat:" src="https://assets-cdn.github.com/images/icons/emoji/octocat.png" height="20" width="20" align="absmiddle">

**Comment by skydir** [comment]
:octocat:

**Comment by agufranov** [comment]
:octocat:

**Comment by AdvTM** [comment]
:octocat:

**Comment by YanLobat** [comment]
:octocat:

**Comment by lancelote** [comment]
:octocat:

**Comment by Gurylev** [comment]
До нодскула осталось три дня.

**Хочу напомнить**: чтобы охранник вас пропустил, вы должны быть в списке. Чтобы попасть в этот список, обязательна регистрация.

@Dan-Ste, @YanLobat, @bmsdave, @ennett50, @plonina, @vforvova особенно это касается вас. Сейчас вас нет в списке заполнивших форму. Пожалуйста, [заполните её](http://grlv.ru/l/nodeschool-jetbrains-registration). Это займёт две минуты.

**Comment by YanLobat** [comment]
@Gurylev Благодарю! А то я так два нодскула пропустил 🤣

**Comment by gucol** [comment]
:octocat:

**Comment by Cirych** [comment]
:octocat:

**Comment by choibalsan** [comment]
:octocat:

**Comment by 7flash** [comment]
:octocat:

**Comment by lxtral** [comment]
:octocat:

**Comment by vovakulikov** [comment]
:octocat

**Comment by vovakulikov** [comment]
:octocat:

**Comment by 3enkal** [comment]
:octocat:

**Comment by idmitriev** [comment]
:octocat:

**Comment by Enkil** [comment]
:octocat:

**Comment by ashtrie** [comment]
:octocat:

**Comment by AlenaDmit** [comment]
:octocat:

**Comment by Marina123456** [comment]
:octocat:

**Comment by juliarainbowx** [comment]
:octocat:

**Comment by ananas7** [comment]
:octocat:

**Comment by nikolaysalinder** [comment]
:octocat:

**Comment by Katysheva** [comment]
:octocat:

**Comment by paninRadario** [comment]
:octocat:

**Comment by nesaulov** [comment]
:octocat:

**Comment by nomi2213** [comment]
:octocat:

**Comment by Margar1ta** [comment]
:octocat:

**Comment by LetoVechno** [comment]
:octocat:

**Comment by Gurylev** [comment]
Регистрация закрыта

**Comment by Gurylev** [comment]
Нодскул в JetBrains уже сегодня! Нужно взять паспорт, ноутбук и голову. До встречи! ;-)
Приходить по адресу: Университетская наб., 7-9-11 к. 5А. Вход со стороны 1 линии В.О. Вам нужно здание с надписью Universe.
