### ISSUE TITLE
18 февраля; Эпик Скилз (Чкаловский пр., 15)

### ISSUE THREAD

**Issue by marinintim** [nodeschool/spb#48]
Привет! :wave:

В эту субботу мы устроим нодскул в Эпике, где и начинали проводить нодскулы в Петербурге. Throwback NodeSchool!

Адрес: **Чкаловский проспект, 15**, пятый этаж, Эпик Скилз, третья аудитория
Время: **14:00**
<figure>
<a href="https://goo.gl/maps/cMLiJLfSN6N2"><img width="796" alt="2017-02-14 14 16 37" src="https://cloud.githubusercontent.com/assets/66025/22927036/a62142b6-f2c8-11e6-99b3-e4da4f88d0b8.png"></a>
<figcaption>Чкаловский пр., 15. Карта кликабельна. Добираться удобнее всего со станции метро Чкаловская (или прогуляться от Петроградской :)</figcaption>
</figure>
<hr />

(если пользуетесь гуглкалендарём, то подписывайтесь на [наш календарь](https://calendar.google.com/calendar/embed?src=qrqp5p2cl6mkheqdin5vhm3k04%40group.calendar.google.com&ctz=Europe/Moscow))

Приходите изучать ноду и реакт, задавать вопросы про веб, знакомиться и пить чай. С собой **нужно взять ноутбук**. Менторить будут @gurylev, @zeckson, и я, @marinintim. **Приносите печеньки**, которые вам нравятся, или малиновое варенье, в общем, что вы там любите.

Для того, чтобы записаться, просто **поставьте `:octocat:`** (:octocat:) комментарием (так мы понимаем, вписываемся ли в помещение, нужно ли звать ещё менторов, надо ли вставать в стойку brace yourself nodeschool is coming, и так далее).

И не забывайте, если бесят письма, можно отключить уведомления для треда в правой колонке :no_bell:.

До встречи! (уже в эту субботу :)

**Comment by Gurylev** [comment]
:octocat:

**Comment by Nesterrr** [comment]
:octocat:

**Comment by agufranov** [comment]
:octocat:

**Comment by kosk** [comment]
:octocat:

**Comment by zeckson** [comment]
:octocat:

**Comment by yurvin** [comment]
:octocat:

**Comment by choibalsan** [comment]
:octocat:

**Comment by beardsleysmind** [comment]
:octocat:

**Comment by GeorgeGorbanev** [comment]
:octocat:

**Comment by mdnkspb** [comment]
:octocat:

**Comment by devVyacheslav** [comment]
:octocat:

**Comment by dojdev** [comment]
🔑

**Comment by Vishnyasuper** [comment]
:octocat:

**Comment by paninRadario** [comment]
:octocat:

**Comment by CKutsenko** [comment]
![image](https://cloud.githubusercontent.com/assets/15856098/22930994/f2bf7556-f2d3-11e6-877d-183072b739b6.png)

**Comment by n1xxx0n** [comment]
:octocat:

**Comment by ERazina** [comment]
:octocat:

**Comment by etki** [comment]
:ocean:

**Comment by JorJeG** [comment]
:octocat:

**Comment by cotang** [comment]
:octocat:

**Comment by nagliy-pirojok** [comment]
:octocat:

**Comment by Jurhard** [comment]
:codocat:

**Comment by shaveko** [comment]
:octocat:

**Comment by preigile** [comment]
:octocat:

**Comment by gucol** [comment]
:octocat:

**Comment by VladBlow** [comment]
:octocat:

**Comment by alexgriss** [comment]
:octocat:

**Comment by lemche** [comment]
:octocat:

**Comment by Avizura** [comment]
:octocat:

**Comment by Greshnick007** [comment]
:octocat:

**Comment by 3enkal** [comment]
:octocat:

**Comment by CubiZm** [comment]
:octocat:

**Comment by ViGo5190** [comment]
:octocat:

**Comment by Dan-Ste** [comment]
:octocat:

**Comment by luxeon89** [comment]
:octocat:

**Comment by bitharmony** [comment]
<img class="emoji" title=":octocat:" alt=":octocat:" src="https://assets-cdn.github.com/images/icons/emoji/octocat.png" height="20" width="20" align="absmiddle">

**Comment by shvgn** [comment]
:octocat:

**Comment by Aerena** [comment]
:octocat:

**Comment by unstoo** [comment]
:octocat:

**Comment by Zveee** [comment]
:octocat:

**Comment by Rigwarl** [comment]
:octocat:

**Comment by bokcart** [comment]
:octocat:

**Comment by iamyahoo** [comment]
:octocat:

**Comment by dhilt** [comment]
:octocat:

**Comment by Gurylev** [comment]
**Нодскул уже сегодня в 14 часов**
Будет круто, если вы заранее [выберете и скачаете воркшоп](https://nodeschool.io/#workshopper-list). Но не переживайте, это можно сделать и на месте.
Обязательно позавтракайте. Завтрак - самый важный приём пищи.
Будет очень круто, если вы захватите печенек.

**Приходите по адресу**
Чкаловский проспект, дом 15. Вход с Ораниенбаумской улицы. 2 дверь от Чкаловского проспекта. 5 этаж.
Не забывайте ноутбуки ;-)

**Comment by gessdead** [comment]
:octocat:

**Comment by AlekseyChepurko** [comment]
:octocat:

**Comment by marinintim** [comment]
Всем спасибо, что пришли! Встретимся на следующем нодскуле :)

-mt
