### ISSUE TITLE
15 апреля 2017 года; Wrike (Свердловская набережная, 44Д)

### ISSUE THREAD

**Issue by Gurylev** [nodeschool/spb#53]
Всем джаваскрипт! 🖖

Не прошёл ещё [мартовский нодскул](https://github.com/nodeschool/spb/issues/49), как публикуется апрельский. Он будет в Wrike. Регистрация обязательна.

Нодскул — это ежемесячные оффлайн-встречи, где участники проходят [уроки](https://nodeschool.io/#workshoppers) с авто-проверками и могут задать вопросы по коду воркшопов опытным кодерам. Эти воркшопы помогают изучить JavaScript от азов до сложных тонкостей библиотек Node.js.

<details>
<summary>Нажми сюда, откроется список того, что поможем понять</summary>

* как запилить сайт на Express, Hapi или Koa
* как превратить сайт в кроссплатформенное приложение на Electron
* как и где хранить данные для ваших приложений
* как упростить жизнь библиотеками
* как упростить работу со стилями при помощи sass или less
* как отлаживать ваш код
* как перейти на современный ES.Next
* как работать с бинарными данными, графикой и аудио
* как написать первые тесты
* как изучить азы и философию ReactJS
* как разобраться в прототипном или в функциональном программировании
* и как отличить лучшие практики написания чистого JS

</details>

&nbsp;
Чтобы попасть на нодскул, обязательно ~[заполните форму](http://grlv.ru/l/nodeschool-50-registration)~ **[места закончились]**. Если вы её не заполните, то не сможете пройти охрану! С собой обязательно нужно взять ноутбук для кодинга, и паспорт/права для преодоления охраны. 

<figure>
<a href="https://yandex.ru/maps/-/C6EpyMIl"><img width="668" alt="NodeSchool Spb в Wrike по адресу Свердловская набережная, 44Д" src="http://grlv.ru/i/nodeschool-map-15.04.2017.jpg"></a>
<figcaption>

**Адрес**: Свердловская набережная, 44Д. Карта кликабельна.
**Дата и время**: 15 апреля с 14 до 18 часов (4 часа)
**Менторы**: @marinintim, @gurylev, @ipelekhan, @zeckson, @mike1pol, @smirina, @nucleartux

Желательно заранее установить [Node.js](https://nodejs.org/) и [Git Bash](https://git-scm.com/), но если что —  мы поможем уже на мероприятии. И ещё хорошо бы выбрать [воркшоп](https://nodeschool.io/#workshoppers) для прохождения выбрать заранее.

Подписывайтесь на наш календарь ([html](https://calendar.google.com/calendar/embed?src=qrqp5p2cl6mkheqdin5vhm3k04%40group.calendar.google.com&ctz=Europe/Moscow), [ical](https://calendar.google.com/calendar/ical/qrqp5p2cl6mkheqdin5vhm3k04%40group.calendar.google.com/public/basic.ics)), там анонс раньше даже, чем на гитхабе.
Приходите изучать ноду и реакт, задавать вопросы про веб, знакомиться и пить чай. С собой нужно взять ноутбук.

Если бесят письма из этой ишьи, можно отключить уведомления для треда в правой колонке
 🔕.
И если есть вопросы - задавайте прямо тут. До встречи!

**Comment by Gurylev** [comment]
[Обязательно зарегистрируйтесь](http://grlv.ru/l/nodeschool-50-registration)

**Comment by ipelekhan** [comment]
:octocat: <sup>*</sup>

<sup>* теперь точно буду</sup>

**Comment by maliyshock** [comment]
:octocat:

**Comment by enjidevelop** [comment]
:octocat:

**Comment by DaryaVeretennikova** [comment]
:octocat:

**Comment by arcticmanic** [comment]
:octocat:

**Comment by Nesterrr** [comment]
:octocat:

**Comment by JuliaBel** [comment]
:octocat:

**Comment by AntonKoshkin** [comment]
:octocat:

**Comment by dojdev** [comment]
🐙

**Comment by SGKuksov** [comment]
:octocat:

**Comment by Ananaskelly** [comment]
:octocat:

**Comment by aqus** [comment]
:octocat:

**Comment by vforvova** [comment]
:octocat:

**Comment by ilyapasyuk** [comment]
:octocat:

**Comment by beardsleysmind** [comment]
:octocat: ..........

**Comment by nekhaevskiy** [comment]
:octocat:

**Comment by loskutNat** [comment]
:octocat:

**Comment by MaxJaison** [comment]
:octocat:

**Comment by iamyahoo** [comment]
:octocat:

**Comment by stk-dmitry** [comment]
:octocat:

**Comment by konurbaev-e** [comment]
Заполнил форму, не смог определиться с воркшопом, написал более подробно в форме почему.
Может, посоветуете что-то?

**Comment by devVyacheslav** [comment]
:octocat:

**Comment by devVyacheslav** [comment]
:octocat:

**Comment by halofourteen** [comment]
:octocat:

**Comment by muzhichin** [comment]
![image](https://cloud.githubusercontent.com/assets/23526342/24461719/07945b30-14b3-11e7-9f3c-47b1895059da.png)

**Comment by karl-kallavus** [comment]
:octocat:

**Comment by yanmhlv** [comment]
:octocat:

**Comment by bokcart** [comment]
:octocat:

**Comment by ruSl0n** [comment]
:octocat:

**Comment by dshved** [comment]
:octocat:

**Comment by alnero** [comment]
:octocat:

**Comment by zeckson** [comment]
:octocat:

**Comment by 1871mg** [comment]
:octocat:

**Comment by GeorgeGorbanev** [comment]
:octocat:

**Comment by vganshin** [comment]
:octocat:

**Comment by agufranov** [comment]
:octocat:

**Comment by Gurylev** [comment]
**Напоминаю**: чтобы пройти пункт охраны в офисе Wrike, вы должны заполнить регистрационную форму и обязательно указать имя и фамилию.

@GeorgeGorbanev, @MaxJaison, @agufranov, @arcticmanic, @dshved, @iamyahoo, @ilyapasyuk, @maliyshock, @muzhichin, @vganshin особенно это касается вас. В списке зарегистрированных вас сейчас нет.

**Comment by Gurylev** [comment]
@konurbaev-e всё зависит от твоего уровня владения языком. Ниже примерный порядок, как я бы рекомендовал проходить. Но это, конечно, индивидуально. И нет никакой необходимости проходить их именно в таком порядке. Достаточно ли у тебя знаний, чтобы не проходить какой-либо воркшоп - это можно определить при встрече после пары вопросов, если есть желание. Хотя на деле часто достаточно посмотреть названия тем в воркшопе.

**Один из вариантов порядка прохождения воркшопов**

Если ты никогда не писал на js, то стоит проходить `javascripting`.

Если базово с js знаком, то можно пройти `scope-chains-closures`, `functional-javascript-workshop`.
Затем `currying-workshopper`, `promise-it-wont-hurt`, `count-to-6`, `esnext-generation`, `learn-generators`, `planetproto`, `js-best-practices`, `bug-clinic`, `test-anything`, `perfschool`, `browserify-adventure`. Порядок соблюдать не обязательно.

Если есть желание разбираться лучше в ноде, то после `scope-chains-closures` можно переходить к `learnyounode`, потом `expressworks`, `makemehapi`, `kick-off-koa` и `learnyoumongo`.

Сейчас в моде реакт, можно поучиться и ему на воркшопах `learnyoureact` и `thinking-in-react`.

**Comment by smirina** [comment]
:octocat:

**Comment by serge1peshcoff** [comment]
:octocat:

**Comment by yurvin** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/octocat.png)

**Comment by ERazina** [comment]
:octocat:

**Comment by Anchello** [comment]
:octocat:

**Comment by misterSerg** [comment]
:octocat:

**Comment by barabaz-z-z** [comment]
:octocat:

**Comment by Alinamur** [comment]
:octocat:

**Comment by nekhaevskiy** [comment]
@Gurylev В [календаре](https://calendar.google.com/calendar/embed?src=qrqp5p2cl6mkheqdin5vhm3k04%40group.calendar.google.com&ctz=Europe/Moscow) нет этого события :(

**Comment by Gurylev** [comment]
@nekhaevskiy ого! Упустил. Спасибо большое! Исправил проблему.

**Comment by EvgeniyGor** [comment]
:octocat:

**Comment by CubiZm** [comment]
:octocat:

**Comment by Gurylev** [comment]
К сожалению, места закончились. Зарегистрироваться больше нельзя.

**Comment by Gurylev** [comment]
<b>Как добраться</b>

<p>В прошлый раз многие плутали и не могли нормально добраться. На этот раз я постараюсь минимизировать эту проблему и расскажу, как добраться до Wrike от ближайших остановок.</p>

<p>В будние дни ездит бесплатный автобус, на котором довольно просто добраться. Но в субботу вам придётся поехать на платном. Не пытайтесь ждать автобус «пять звёзд».</p>

<p>Для надёжности на случай, если интернет не будет ловить, скачайте на телефон фотки вашего маршрута от остановки, до которой поедете.</p>

<br>
<details>
    <summary>От ст. м. Пл. Ленина</summary>
    <details>
        <summary>— на маршрутке К254 или на автобусах 106, 133, 37 (рекомендую)</summary>
<hr>
        Ждите маршрутку К254 или автобусы 106, 133, 37 на <a href="http://grlv.ru/i/j7aa7.png" target="_blank">этой остановке</a>.<br>
        Нужно проехать 8 остановок до остановки «Пискарёвский проспект».<br>
        Воспользуйтесь построенным маршрутом на <a href="https://yandex.ru/maps/-/C6Ut70~d" target="_blank">яндекс.картах</a>, на <a href="https://goo.gl/prUhxD" target="_blank">гугл картах</a> и на <a href="http://go.2gis.com/gxzht" target="_blank">2гис</a>.<br>
        А когда доедете, идите по фото-инструкции<br><a href="https://goo.gl/photos/AKEXY68o2wCqNnE26" target="_blank">как дойти до Wrike от перекрёстка Полюстровского и Пискарёвского проспектов</a>. Заранее посмотрите <a href="http://grlv.ru/i/3s629.png" target="_blank">на карте</a>.
<hr>
    </details>
    <details>
        <summary>— на маршрутках К106, К137, К530</summary>
<hr>
        Ждите маршрутки К106, К137, К530 на <a href="http://grlv.ru/i/vzroa.png" target="_blank">этой остановке</a>.<br>
        Нужно проехать 4 остановки до остановки «Пискарёвский проспект».<br>
        Воспользуйтесь построенным маршрутом на <a href="https://yandex.ru/maps/-/C6UxEAp-" target="_blank">яндекс.картах</a> и на <a href="http://go.2gis.com/rku2q" target="_blank">2гис</a>.<br>
        А когда доедете, идите по фото-инструкции<br><a href="https://goo.gl/photos/Dgcq7TsT1EQYtdeV7" target="_blank">как дойти до Wrike от перекрёстка Пискарёвского проспекта и шоссе Революции</a>. Заранее посмотрите <a href="http://grlv.ru/i/awhtd.png" target="_blank">на карте</a>.
<hr>
    </details>
</details>

<br>
<details>
<summary>От ст. м. Новочеркасская</summary>
<hr>
        Выходить удобно через 6 выход. Ждите маршрутку К6 или трамвай 23 на <a href="http://grlv.ru/i/0tmvz.png" target="_blank">этой остановке</a>.<br>
        Нужно проехать 8 остановок до остановки «Пискарёвский проспект».<br>
        Воспользуйтесь построенным маршрутом на <a href="https://yandex.ru/maps/-/C6UxE8Zm" target="_blank">яндекс.картах</a> и на <a href="http://go.2gis.com/0pkhr" target="_blank">2гис</a>.<br>
        А когда доедете, идите по фото-инструкции<br><a href="https://goo.gl/photos/AKEXY68o2wCqNnE26" target="_blank">как дойти до Wrike от перекрёстка Полюстровского и Пискарёвского проспектов</a>. Заранее посмотрите <a href="http://grlv.ru/i/3s629.png" target="_blank">на карте</a>.
<hr>
</details>
<br>
<p><b>Парковка</b> платная, если вы хотите оставить свою машину на территории бизнес-парка «Полюстрово». Если вы на своей машине, оставьте её где-нибудь неподалёку. Например, на улице Жукова.</p>

<p><b>Убер</b> или любое другое такси сможет довезти вас до входа в БЦ Лето. При въезде водителю потребуется получить талон на въезд, <a href="https://lh3.googleusercontent.com/-6zuAH58XNfVlEyC8DbRh152ZT_hyDzMjmV_nK-Lf62dj2fM8mclz-fH7mq-87iBOSdwvcTW6YCAGdW3OBC8i4b7ToBSJ29eKjgOySwgvJNF53YuJ9eLA05xR_cpbNVpITO3NbjaW0rnqVS46LsIyiJ9ascUB2c5KKgDlTP0DE_XDaM_rvKyc8xIk_k8wsb5hAFc6WTxgVhYKQ_7twAc_NfV54BCLBMOeov5KA5Qv6hS1XyotLC0Ws6RikrqiuYYm8V2flRzlWI2TZJIymh1XdcnyfPObaHxTwBCdwLOLyNdHtmXBXkaC4qj_I6tFlOanGfutEcSE_c9cVviCfDLXghE5vTZI_J_ZgR4rXDB_MYcfY5wEybksK8kft8lcinkMzdalKAC-VcSnML2yXE2dXiHjsag3AZTq8fRJBvLxOC0uqz8GL2fEf6ipL8nwzYK3aDS6Ot1fGN2eKT9LnsX5Y604BAZxzTJPrWOamDwaLotzL7JziJi5RC6VQUS5Oofcmi2W2JHnXQYkaJwKmDuDpRnizpPRBv7hoE21manXYrDKrxZ9-uZ-fOWP5J4BdHZmxNJFo3ECCRBallQ8Q2cyz_-cAoaA1EbMwObD2H1AJ1GF2HTuTtWQtD0D_ZqfzjDBwWhm95cHBgDqQL-FfTCcq0ll_Jc8piIXeyMk5fsLtI=w1276-h958-no" target="_blank">это просто</a>.</p>

<p><b>Лайфхак</b>: включите в смартфоне геопозицию и воспользуйтесь приложением <a href="https://mobile.yandex.ru/apps/android/transport" target="_blank">яндекс.транспорт</a>. Настройте маршрут и садитесь на подходящий транспорт. В приложении есть гео-будильник, он не даст проехать мимо. Знайте: будильник сигналит, когда вы на остановку раньше, чем ваша конечная. Не нужно резко вскакивать и выбегать при сигнале на остановке.</p>

<p><b>Оффлайн</b>: Этот комментарий можно скачать в Pocket или Evernote для оффлайн-доступа <a href="http://s.codepen.io/fogrew/debug/jmOzPa" target="_blank">по этой ссылке</a>. Скачать фотки придётся отдельно из альбомов (там есть функция «скачать все»).</p>

**Comment by Gurylev** [comment]
Нодскул уже завтра! Не забыли? Будет круто, если вы ещё и воркшоп заранее выберете. https://nodeschool.io/#workshopper-list

**Comment by ruSl0n** [comment]
Я не помню, зарегистрирован ли я? Можете помочь ? ФИО: Бакиров Руслан Рифгатович

**Comment by Gurylev** [comment]
@ruSl0n сори, что так поздно пишу, но ты ещё вполне себе можешь успеть: да, ты есть в списках. Приходи обязательно.

**Comment by Gurylev** [comment]
Всем спасибо, что пришли! Вы сегодня были чертовски круты и самостоятельны. Это очень круто!
