### ISSUE TITLE
10 июня 2017 года; T-Systems (13-линия В.О., д.14)

### ISSUE THREAD

**Issue by Gurylev** [nodeschool/spb#54]
Наступило лето! 😎 ☀️ Но нам не помешает учиться джаваскрипту 🤠

Мы оказались очень заняты в мае, поэтому нодскула не было. Но вы не огорчайтесь! Мы не пропали насовсем. Пришла пора рассказать про нодскул в июне.

В июне мы проведём нодскул в офисе T-Systems. ~[регистрация](http://bit.ly/nodeschool-spb-54)~ (закрыта)
А октокота писать в ишью совершенно не обязательно 😉

<details>
<summary>Что такое нодскул?</summary>

Нодскул — это ежемесячное оффлайн-мероприятие, где участники проходят [уроки](https://nodeschool.io/#workshoppers) с авто-проверками и могут задать вопросы по коду уроков опытным кодерам. Эти воркшопы (так мы называем такие уроки) помогают изучить JavaScript от азов до сложных тонкостей библиотек Node.js, а также немного других фронтендерских технологий.

</details>

<details>
<summary>Нажми сюда, откроется список того, что поможем понять</summary>

* как запилить сайт на Express, Hapi или Koa
* как превратить сайт в кроссплатформенное приложение на Electron
* как и где хранить данные для ваших приложений
* как упростить жизнь библиотеками
* как упростить работу со стилями при помощи sass или less
* как отлаживать ваш код
* как перейти на современный ES.Next
* как работать с бинарными данными, графикой и аудио
* как написать первые тесты
* как изучить азы и философию React
* как разобраться в прототипном и в функциональном программировании
* и как отличить лучшие практики написания чистого JS

</details>

&nbsp;
Чтобы попасть на нодскул, обязательно ~[заполните форму](http://bit.ly/nodeschool-spb-54)~ (регистрация закрыта). Если вы её не заполните, то не сможете пройти охрану!

<figure>
<a href="https://yandex.ru/maps/-/CBQAJPabcD"><img width="668" alt="NodeSchool Spb в T-Systems по адресу 13-линия В.О., д.14" src="https://cloud.githubusercontent.com/assets/484159/26582099/74dfb6a6-4548-11e7-84ba-3a6f676d819d.jpg"></a>
<figcaption>

**Адрес**: 13-линия В.О., д.14. Карта кликабельна.
**Дата и время**: 10 июня с 14 до 18 часов (4 часа)
**Менторы**: @marinintim, @gurylev, @zeckson, @vforvova, @smirina, @nucleartux

Желательно заранее установить [Node.js](https://nodejs.org/) и [Git Bash](https://git-scm.com/), но если что —  мы поможем уже на мероприятии. Хорошо бы выбрать [воркшоп](https://nodeschool.io/#workshoppers) для прохождения выбрать заранее. С собой обязательно нужно взять ноутбук для кодинга.

Подписывайтесь на наш календарь ([html](https://calendar.google.com/calendar/embed?src=qrqp5p2cl6mkheqdin5vhm3k04%40group.calendar.google.com&ctz=Europe/Moscow), [ical](https://calendar.google.com/calendar/ical/qrqp5p2cl6mkheqdin5vhm3k04%40group.calendar.google.com/public/basic.ics)), там анонс раньше даже, чем на гитхабе.
Приходите изучать ноду и реакт, задавать вопросы про веб, знакомиться и пить чай.

----
Если бесят письма из этой ишьи, можно отключить уведомления в правой колонке 🔕.
И если есть вопросы - задавайте прямо тут. До встречи!

**Comment by zeckson** [comment]
> Дата и время: 10 апреля с 14 до 18 часов (4 часа)

**Comment by bokcart** [comment]
:octocat:

**Comment by romankazakov** [comment]
:octocat:

**Comment by GeorgeGorbanev** [comment]
:octocat:

**Comment by Nesterrr** [comment]
:octocat:

**Comment by kosk** [comment]
:octocat:

**Comment by AntonKoshkin** [comment]
:octocat:

**Comment by Gurylev** [comment]
Я понимаю, что вы привыкли и традиция, но, если что, октокота писать в ишью совершенно не обязательно 😉

**Comment by AntonKoshkin** [comment]
уже деприкейтед? ну епт...

**Comment by Gurylev** [comment]
@AntonKoshkin `yarn upgrade`

**Comment by AntonKoshkin** [comment]
ярн уже не нужен, нпм5 же

**Comment by luxeon89** [comment]
:octocat:

**Comment by Gurylev** [comment]
@AntonKoshkin ой всё (на самом деле ярн быстрее. а ещё он мне больше нравится. а ещё это всё субъективщина)

**Comment by zeihlis** [comment]
@Gurylev потестил на наших проектах сборку на седьмой ноде и пятом нмпе и внезапно нпм5 быстрее ставит на 10-15% в среднем

**Comment by maliyshock** [comment]
:octocat:

**Comment by MaceEsina** [comment]
:octocat:

**Comment by dojdev** [comment]
👋

**Comment by SGKuksov** [comment]
:cat:, :octocat:

**Comment by gossoudarev** [comment]
:octocat:

**Comment by navinweb** [comment]
:octocat:

**Comment by vlshat** [comment]
:octocat:

**Comment by sutarmin** [comment]
А что за традиция такая с октокотом, расскажите? А то вдруг это пропуск на вечеринку, а я не знаю.

**Comment by ERazina** [comment]
:octocat:

**Comment by Anchello** [comment]
:octocat:

**Comment by Gurylev** [comment]
Регистрация закрыта

**Comment by nicaraguanec** [comment]
Привет!
По независящим от меня причинам, не смогу завтра придти.
@Gurylev у вас есть еще одно свободное место:)

**Comment by mantrovad** [comment]
Претендую на освободившееся место)

**Comment by vlshat** [comment]
Тоже не смогу придти

**Comment by lancelote** [comment]
Я бы пришел, если есть свободное место

**Comment by Gurylev** [comment]
### Как проехать до T-Systems?
Ехать сюда: 13-линия В.О., д.14
Постройте маршрут на [яндекс.картах](https://yandex.ru/maps/-/CBQeyWtPcC), [гугл картах](https://goo.gl/maps/gwaubwVKXhQ2) или [2гис](http://go.2gis.com/hzq1y)

### Как пройти на нодскул?
БЦ Елизаветинский, вход под козырек с улицы 13-я линия В.О. На охране пододите к девушке со списком, назовите фамилию, пройдите в помещение по указателям.
</details>

**Comment by Gurylev** [comment]
Списки уже отданы на охрану, поменять их не получится.

**Comment by devVyacheslav** [comment]
:octocat:

**Comment by Gurylev** [comment]
Всем спасибо за участие. Вы очень круто справлялись!
[Вот тут фотки вашего серьёзного кодинга](https://vk.com/wall-95068629_148) 🥇 
Подписывайтесь на наши новостные каналы, чтобы не пропустить следующие нодскулы.

Этот репозиторий на гитхабе (кнопка Watch сверху),
[группа вконтакте](https://vk.com/nodeschoolspb),
[группа в фейсбуке](https://www.facebook.com/groups/nodeschoolspb/),
и [твиттер](https://mobile.twitter.com/nodeschoolspb).
