### ISSUE TITLE
29 июля 2017 года; Одноклассники (ул. Херсонская 12-14, БЦ «Ренессанс Правда»)

### ISSUE THREAD

**Issue by Gurylev** [nodeschool/spb#55]
Лето в самом разгаре! 😎 ☀️ Хоть солнца в солнечном Петербурге и немного, но можно встретиться и немного облучить свою кожу от экрана монитора! 💻

Мы проведем июльский нодскул 29 июля в офисе «[ok.ru](https://ok.ru/)».
Всё что для этого нужно от вас — ~[зарегистрироваться](https://vk.cc/6Ra9J0)~ **(регистрация закрыта)** и взять с собой паспорт, чтоб пройти.

А октокота писать в ишью совершенно не обязательно 😉

<details>
<summary>Что такое нодскул?</summary>

Нодскул — это ежемесячное оффлайн-мероприятие, где участники проходят [уроки](https://nodeschool.io/#workshoppers) с авто-проверками и могут задать вопросы по коду уроков опытным кодерам. Эти воркшопы (так мы называем такие уроки) помогают изучить JavaScript от азов до сложных тонкостей библиотек Node.js, а также немного других фронтендерских технологий.

</details>

<details>
<summary>Нажми сюда, откроется список того, что поможем понять</summary>

* как запилить сайт на Express, Hapi или Koa
* как превратить сайт в кроссплатформенное приложение на Electron
* как и где хранить данные для ваших приложений
* как упростить жизнь библиотеками
* как упростить работу со стилями при помощи sass или less
* как отлаживать ваш код
* как перейти на современный ES.Next
* как работать с бинарными данными, графикой и аудио
* как написать первые тесты
* как изучить азы и философию React
* как разобраться в прототипном и в функциональном программировании
* и как отличить лучшие практики написания чистого JS

</details>

&nbsp;
Чтобы **попасть на нодскул**, обязательно ~[заполните форму](https://vk.cc/6Ra9J0)~ **(регистрация закрыта)**. **Если вы её не заполните, то не сможете пройти самое сложное задание — охрану!**

<figure>
<a href="https://yandex.ru/maps/-/C6BLIF46"><img width="600" height="450" alt="NodeSchool Spb в OK.ru по адресу ул. Херсонская 12-14" src="https://static-maps.yandex.ru/1.x/?l=map&lang=ru_RU&ll=30.379125217406937%2C59.92810030924567&origin=jsapi-constructor&pt=30.381005%2C59.928654%2Cpm2bll&size=600%2C450&z=15"></a>
<figcaption>

**Адрес**: ул. Херсонская 12-14, БЦ «Ренессанс Правда». Карта кликабельна.
**Дата и время**: 29 июля с 14 до 18 часов (4 часа)
**Менторы**: @marinintim, @gurylev, @zeckson, @vforvova, @smirina, @nucleartux, @mike1pol, @hypnosphi 

Желательно заранее установить [Node.js](https://nodejs.org/) и [Git Bash](https://git-scm.com/), но если что —  мы поможем уже на мероприятии. Хорошо бы выбрать [воркшоп](https://nodeschool.io/#workshoppers) для прохождения выбрать заранее. С собой обязательно нужно взять ноутбук для кодинга.

Подписывайтесь на наш календарь ([html](https://calendar.google.com/calendar/embed?src=qrqp5p2cl6mkheqdin5vhm3k04%40group.calendar.google.com&ctz=Europe/Moscow), [ical](https://calendar.google.com/calendar/ical/qrqp5p2cl6mkheqdin5vhm3k04%40group.calendar.google.com/public/basic.ics)), там анонс раньше даже, чем на гитхабе.
Приходите изучать ноду и реакт, задавать вопросы про веб, знакомиться и пить чай.

----
Если бесят письма из этой ишьи, можно отключить уведомления в правой колонке 🔕.
И если есть вопросы - задавайте прямо тут. До встречи!

**Comment by Gurylev** [comment]
Напоминаю: октокота писать в ишью совершенно не обязательно 😉 Нужна только регистрация через [форму](http://bit.ly/nodeschool-spb-55-reg).

**Comment by marinintim** [comment]
:octocat:!

**Comment by mike1pol** [comment]
📣

**Comment by Gurylev** [comment]
Тяжко :)

**Comment by eveness** [comment]
Пачиму только один воркшоп выбрать можно? :relieved:

**Comment by Gurylev** [comment]
@eveness пройти можно больше, если получится. Нам важно, с какого вы начнёте :)

**Comment by SGKuksov** [comment]
Эх.. Прошли те времена когда одного :октокота: хватало для регистрации. Прошли..

**Comment by Gurylev** [comment]
Если вдруг вы из тех, кому роскомнадзор заблокировал ссылку на регистрацию, то воспользуйтесь этой: [https://vk.cc/6Ra9J0](https://vk.cc/6Ra9J0)

**Comment by tpqDnF** [comment]
@eveness там же есть пункт "Другое". 
И написать все те, которые есть желание посетить. 
Как вариант

**Comment by 2gnc** [comment]
Друзья, какой уровень участников? Интересует "как разобраться в прототипном и в функциональном программировании" и "лучшие практики.."? Js немного умею, node - опыта нет от слова совсем

**Comment by nucleartux** [comment]
Уровень от нулевого практически :)

**Comment by headfire94** [comment]
На почту должно упасть что-то после регистрации? У меня пусто)

**Comment by Gurylev** [comment]
@headfire94 должна прийти копия заполненной формы. Можете не переживать, ник headfire94 есть в списке зарегистрировавшихся.

**Comment by Gurylev** [comment]
Регистрация закрыта

**Comment by il12** [comment]
Прошу прощения, не смогу завтра прийти

**Comment by Gurylev** [comment]
@il12 ничего страшного. Приходи в другой раз ;-) Нодскул ежемесячный.

**Comment by Gurylev** [comment]
### Как попасть на нодскул?
Офис ОК.ru находится в БЦ «Ренессанс Правда».
Можно дойти до него пешком примерно за 10 минут от станций метро [пл. Александра Невского](https://yandex.ru/maps/-/CBQ2NPbqlA) или [пл. Восстания](https://yandex.ru/maps/-/CBQ2NPRVHC). Вход с Исполкомской улицы. [Выглядит так](http://grlv.ru/i/eow2w.png).

От входа идите прямо к пункту охраны. Там нужно будет предъявить паспорт, чтоб вас отметили в списке пришедших. Без паспорта охрана вас не пропустит, это требование безопасности бизнес-центра. Когда вас пропустят — езжайте на 7 этаж в лифте. После лифта направо — в офис Одноклассников. Вуаля! Вы на месте.

**Comment by Gurylev** [comment]
Спасибо всем, кто пришёл на июльский нодскул!
[Уже выложили фотки](https://photos.app.goo.gl/bKVBvWIFLdP7BuOt1) 😉

Подписывайтесь на этот репозиторий и наши социалки, там будут анонсы нодскулов:
[вк](https://vk.com/nodeschoolspb), [фб](https://www.facebook.com/groups/nodeschoolspb/), тг [канал](https://t.me/nodeschoolspb) и [флудилка](https://t.me/nodeschoolspb_group)
Августовский нодскул [уже анонсировали](https://github.com/nodeschool/spb/issues/55)!
