### ISSUE TITLE
26 августа 2017 года; SPACE307 (ул. Кропоткина 1, БЦ Сенатор)

### ISSUE THREAD

**Issue by Gurylev** [nodeschool/spb#59]
Следующий нодскул мы проведём 26 августа. В этот раз соберёмся в офисе компании SPACE307. 

~[Регистрируйтесь](https://vk.cc/6W3ki4)~ **Регистрация закрыта!**

<details>
<summary>Что такое нодскул?</summary>

Нодскул — это ежемесячное оффлайн-мероприятие, где участники проходят [уроки](https://nodeschool.io/#workshoppers) с авто-проверками и могут задать вопросы по коду уроков опытным кодерам. Эти воркшопы (так мы называем такие уроки) помогают изучить JavaScript от азов до сложных тонкостей библиотек Node.js, а также немного других фронтендерских технологий.

</details>

<details>
<summary>На нодскуле можно узнать</summary>

* как запилить сайт на Express, Hapi или Koa
* как превратить сайт в кроссплатформенное приложение на Electron
* как и где хранить данные для ваших приложений
* как упростить жизнь библиотеками
* как упростить работу со стилями при помощи sass или less
* как отлаживать ваш код
* как перейти на современный ES.Next
* как работать с бинарными данными, графикой и аудио
* как написать первые тесты
* как изучить азы и философию React
* как разобраться в прототипном и в функциональном программировании
* и как отличить лучшие практики написания чистого JS

</details>

&nbsp;
Чтобы попасть на нодскул, нужно было заполнить форму. Теперь поздно, регистрация уже закрыта. **Если вы не регистрировались, то охрана бизнес-центра вас не пропустит**

**Адрес**: ст. м. Горьковская, ул. Кропоткина 1, БЦ Сенатор. Карта кликабельна.
**Дата и время**: 26 августа с 14 до 18 часов (4 часа)
**Менторы**: @marinintim, @gurylev, @zeckson, @nucleartux, @bmsdave, @scink 

<figure>
<a href="https://yandex.ru/maps/-/CBQ2rKbo0D"><img width="668" height="424" alt="NodeSchool Spb в SPACE307 по адресу ул. Кропоткина 1" src="http://grlv.ru/i/fs96y.png"></a>
<figcaption>

Желательно заранее установить [Node.js](https://nodejs.org/) и [Git Bash](https://git-scm.com/), но если что —  мы поможем уже на мероприятии. Хорошо бы выбрать [воркшоп](https://nodeschool.io/#workshoppers) для прохождения выбрать заранее. С собой обязательно нужно взять ноутбук для кодинга.

Подписывайтесь на наш календарь ([html](https://vk.cc/6W3ER2), [ical](https://vk.cc/6W3EWR)), там анонс раньше даже, чем на гитхабе.
Приходите изучать ноду и реакт, задавать вопросы про веб, знакомиться и пить чай.

----
Здесь в комментариях можно задать любые вопросы по мероприятию.
Если бесят письма из этой ишьи, можно отключить уведомления в правой колонке 🔕.
И если есть вопросы - задавайте прямо тут. До встречи!

**Comment by ruSl0n** [comment]
⛰

**Comment by mike1pol** [comment]
🍻

**Comment by Gurylev** [comment]
Регистрация закроется в полночь! Поторопитесь 🐎

**Comment by Gurylev** [comment]
### Как попасть на нодскул?
Офис space307 находится в БЦ Сенатор по адресу Кропоткина, 1. 
Можно дойти до него пешком примерно за 10 минут от станции метро [Горьковская](https://yandex.ru/maps/-/CBUyRXC-sD). Вход с Пушкарского переулка. [Выглядит так](http://grlv.ru/i/0nzir.png).

От входа идите прямо к пункту охраны. Там сказать имя и фамилию, чтоб вас отметили в списке пришедших. Когда вас пропустят — езжайте в лифте на 3 этаж и идите по указателям. Так вы найдёте нодскул.

**Comment by Gurylev** [comment]
Спасибо всем, кто пришёл на августовский нодскул! Вы молодцы!
Как только будут фоточки, мы напишем в социалочках.

Подписывайтесь на наш календарь ([html](https://vk.cc/6W3ER2), [ical](https://vk.cc/6W3EWR)), информационные каналы [в телеграме](https://t.me/nodeschoolspb), [вконтакте](https://vk.com/nodeschoolspb), [в фейбсуке](https://www.facebook.com/groups/nodeschoolspb/) и [в твиттере](https://twitter.com/nodeschoolspb).
Приходите общаться и задавать вопросы в чаты [в телеграме](https://t.me/nodeschoolspb_group) и [в slack](http://nodeschool.ru/slack).

[И приходите в сентябре!](https://github.com/nodeschool/spb/issues/60)
