### ISSUE TITLE
Нодскул 31.05

### ISSUE THREAD

**Issue by marinintim** [nodeschool/spb#6]
Итак, 31 мая.

Проводят @marinintim и @ipelekhan

**Comment by vkfont** [comment]
аве, не прошло и полугода :)
уже известно где и в каком формате? менторы есть или надо собирать?

**Comment by ipelekhan** [comment]
@vkfont место есть, с форматом вроде бы определились :-)
Подробности будут где-то здесь: https://vk.com/nodeschool_1

**Comment by isRuslan** [comment]
Всем привет!
Нодскул пришел в петербург, очень круто!

Я хочу познакомится, я не так давно сделал воркшоппер [Learn generators](https://github.com/isRuslan/learn-generators) по изучению генераторов в ES6 JS. Я могу попробовать провести его, если это интересно.

Так же я немного участвовал в разработке самого workshopper фреймворка, в частности добавил туда русскую локализацию. И перевел [learnyounode](https://github.com/workshopper/learnyounode) на русский язык. Переводом я не горжусь, его нужно вычитывать хорошенько, но в целом он не врет и о чем задание вроде понять можно.

Узнал я о том что будет это мероприятие только что и практически случайно. В ином случае можно было бы лучше вычитать перевод для `learnyounode` и перевести `learn-generators` на русский.

**Comment by ipelekhan** [comment]
@isRuslan, привет!

Думаю до 31-го всё сказанное тобой будет сложно сделать, но следующее мероприятие не за горами, я надеюсь. Так что добро пожаловать :wink:

**Comment by isRuslan** [comment]
Окей, тогда `learn-generators` подготовлю на следующее мероприятие.

**Comment by kweyjibo** [comment]
me & @fromanywhere

**Comment by vlkosinov** [comment]
Очень круто, что эта встреча состоялась. @marinintim реально молодец, старательно помогал, тем у кого что-то не получалось и отвечал на все вопросы :thumbsup: Почаще такие встречи нужно проводить. В дальнейшем, думаю, стоит четко обозначать тему встречи, подробно ее раскрывать во вступительной части и заранее скидывать материал по теме. С удовольствием сам бы рассказал, например, про промисы.

**Comment by marinintim** [comment]
@vlkosinov Я запомнил про промисы!
