### ISSUE TITLE
23 сентября 2017 года; EPAM (ул. Заставская, 22А, БЦ МегаПАРК)

### ISSUE THREAD

**Issue by Gurylev** [nodeschool/spb#60]
<a href="https://www.epam-group.ru/" target="_blank"><img align="right" src="http://quests.by/wp-content/uploads/2015/02/epam-200x120.png" alt="EPAM"></a>23 сентября нодскул будет в EPAM.
Это всё, что вам нужно знать в сентябре.

### [=  регистрация закрыта, места кончились =]

<details>
<summary>Что такое нодскул?</summary>

Нодскул — это ежемесячное оффлайн-мероприятие, где участники проходят [уроки](https://nodeschool.io/#workshoppers) с авто-проверками и могут задать вопросы по коду уроков опытным кодерам. Эти воркшопы (так мы называем такие уроки) помогают изучить JavaScript на фронтенде и бекенде от самых азов до сложных тонкостей фреймворков и библиотек, а также многие другие фронтендерские технологии, без которых в реальной разработке никак.

</details>

<details>
<summary>Что можно узнать на нодскуле?</summary>

На нодскуле можно узнать

* [как](https://github.com/stevekane/promise-it-wont-hurt) [писать](https://github.com/domenic/count-to-6) [современный](https://github.com/isRuslan/learn-generators) [JavaScript](https://github.com/jesstelford/esnext-generation)
* как разобраться в [прототипном](https://github.com/sporto/planetproto) и в [функциональном](https://github.com/timoxley/functional-javascript-workshop) программировании
* и как отличить [лучшие практики написания чистого JS](https://github.com/excellalabs/js-best-practices-workshopper)
* как упростить жизнь [библиотеками](https://github.com/mdunisch/lololodash)
* как [отлаживать](https://github.com/othiym23/bug-clinic) ваш код
* как написать [первые тесты](https://github.com/finnp/test-anything)
* как изучить [азы](https://github.com/workshopper/learnyoureact) и [философию](https://github.com/asbjornenge/thinking-in-react) React
* как упростить работу со стилями при помощи [sass](https://github.com/workshopper/learn-sass) или [less](https://github.com/gnerkus/less-is-more)
* как запилить сайт на [Express](https://github.com/azat-co/expressworks), [Hapi](https://github.com/hapijs/makemehapi) или [Koa](https://github.com/koajs/kick-off-koa)
* как и где хранить данные для ваших приложений ([mongo](https://github.com/evanlucas/learnyoumongo), [counchDB](https://github.com/robertkowalski/learnyoucouchdb), [levelDB](https://github.com/workshopper/levelmeup))
* как превратить сайт в кроссплатформенное приложение на [Electron](https://github.com/maxogden/elementary-electron)
* как работать с [бинарными данными](https://www.github.com/maxogden/bytewiser), [графикой](https://github.com/gl-modules/shader-school) и [аудио](https://github.com/mmckegg/web-audio-school)

</details>

&nbsp;
Чтобы попасть на нодскул, нужно было заполнить регистрационную форму. Если вы не успели, то уже не попадёте на этот нодскул, так что караульте новости и регайтесь на следующий.
## Обязательно возьмите с собой паспорт
**Без этого вы не сможете пройти охрану!**

### Приходите 😉
**Адрес**: ст. м. Московские ворота, ул. Заставская, 22А, БЦ МегаПарк, 7 этаж.
**Дата и время**: 23 сентября с 14:00 до 18:00 (4 часа) [ [добавить в календарь](https://vk.cc/72DI4r) ]
**Менторы**: @marinintim, @gurylev, @agufranov, @bmsdave, @scink, @mike1pol, @glukki

<figure>
<a href="https://yandex.ru/maps/-/CBU5iRXwSA"><img width="668" height="424" alt="NodeSchool Spb в EPAM по адресу ул. Кропоткина 1" src="http://grlv.ru/i/1wyao.png"></a>
<figcaption>

### Будьте готовы 💻
Желательно заранее установить [Node.js](https://nodejs.org/) и [Git Bash](https://git-scm.com/), но если что —  мы поможем уже на мероприятии. Хорошо бы выбрать [воркшоп](https://nodeschool.io/#workshoppers) для прохождения заранее. С собой обязательно нужно взять ноутбук для кодинга и паспорт, чтоб пройти охрану БЦ МегаПарк.

### Будьте в курсе 🔔
Подписывайтесь на наш календарь ([html](https://vk.cc/6W3ER2), [ical](https://vk.cc/6W3EWR)), там анонс раньше даже, чем на гитхабе.
Подписывайтесь на наши инфо-каналы [в телеграме](https://t.me/nodeschoolspb), [вконтакте](https://vk.com/nodeschoolspb), [в фейбсуке](https://www.facebook.com/groups/nodeschoolspb/) и [в твиттере](https://twitter.com/nodeschoolspb).
Приходите общаться в нашу [флудилку в телеграме](https://t.me/nodeschoolspb_group) и в [slack](http://nodeschool.ru/slack).

Приходите изучать ноду и реакт, задавать вопросы, знакомиться, кушать пиццу и пить чай.

----
Здесь в комментариях можно задать любые вопросы по мероприятию.
До встречи!

**Comment by ruSl0n** [comment]
🍒

**Comment by ERazina** [comment]
🅾️

**Comment by marinintim** [comment]
📆 🤙

**Comment by Gurylev** [comment]
Вы все как будто хотите что-то сказать..)

**Comment by yvinokurov** [comment]
:octocat:

**Comment by Gurylev** [comment]
Регистрация закрыта, места кончились.

**Comment by paninRadario** [comment]
5 мест что ли?

**Comment by nucleartux** [comment]
Здесь не регистрация, регистрация по ссылке в issue.

**Comment by Gurylev** [comment]
По уже удалённой ссылке. Места закончились, ссылка больше не нужна.

**Comment by glukki** [comment]
✌️

**Comment by Gurylev** [comment]
Спасибо всем, кто пришёл на сентябрьский нодскул! Вы 🔥!
Как только будут фоточки, мы напишем в социалочках.

Подписывайтесь на наш календарь ([html](https://vk.cc/6W3ER2), [ical](https://vk.cc/6W3EWR)), информационные каналы [в телеграме](https://t.me/nodeschoolspb), [вконтакте](https://vk.com/nodeschoolspb), [в фейбсуке](https://www.facebook.com/groups/nodeschoolspb/) и [в твиттере](https://twitter.com/nodeschoolspb), оттуда вы узнаете информацию об октябрьском нодскуле.
Приходите общаться и задавать вопросы в чаты [в телеграме](https://t.me/nodeschoolspb_group) и [в slack](http://nodeschool.ru/slack).
