### ISSUE TITLE
29 октября (воскресенье), SPACE307 (Кропоткина, 1)

### ISSUE THREAD

**Issue by marinintim** [nodeschool/spb#62]
Привет! Мы проведём очередной нодскул в **это воскресенье** (29 октября), в офисе SPACE307.

**Адрес**:  Кропоткина, 1, БЦ Сенатор, офис компании SPACE307 ([на карте](https://goo.gl/maps/PnmKBD1pSCB2))
**Время**: это _воскресенье_, 14:00–18:00 ([добавить в свой календарь](https://calendar.google.com/event?action=TEMPLATE&tmeid=N2xrYjlsbTg5MXFhNWM5aWc3NGZiZzBvNG8gcXJxcDVwMmNsNm1raGVxZGluNXZobTNrMDRAZw&tmsrc=qrqp5p2cl6mkheqdin5vhm3k04%40group.calendar.google.com))
**Формат**: проходим воркшопы с nodeschool.io!
**Менторы**: @marinintim, @nucleartux, @gurylev, @zeckson, @mike1pol 

Соберёмся в воскресенье покодить и попроходить воркшопы, пока ещё не совсем дико холодно! Приходите и не забудьте взять с собой ноутбук :)

## Как зарегистрироваться
В три простых шага!

1. Оставить в комментариях :octocat: (`:octocat:`)
2. Заполнить форму по ссылке: https://goo.gl/forms/UwmuoycLjEIdWLKZ2 — это нужно для охраны бизнес-центра.
3. Прийти с ноутбуком (для воркшопов) и паспортом (для охраны)

## Как добраться
Удобнее всего добраться пешком от метро Петроградская, Чкаловская, или Горьковская.

### Вход

Вход выглядит вот так:

<img width="965" alt="БЦ Сенатор" src="https://user-images.githubusercontent.com/66025/31947008-09cbd4dc-b8dc-11e7-8beb-2570f7192e9c.png">

### Горьковская

Дойти до Австрийской площади, повернуть налево на улицу Мира, затем направо.

<img width="758" alt="Карта от метро Горьковская" src="https://user-images.githubusercontent.com/66025/31947044-21ba5a64-b8dc-11e7-83e0-8a6679c60cfa.png">

### Чкаловская

Дойти до Большого проспекта ПС, повернуть налево до улицы Ленина, повернуть направо и идти до конца.

<img width="949" alt="Карта от метро Чкаловская" src="https://user-images.githubusercontent.com/66025/31947100-36563d8a-b8dc-11e7-843c-e5a72593a4d2.png">

### Петроградская

Дойти до Большой Пушкарской, потом повернуть налево на Кронверкскую.

<img width="625" alt="Карта от метро Петроградская" src="https://user-images.githubusercontent.com/66025/31947112-3c2221fc-b8dc-11e7-976d-ff070f6cded4.png">

## Важные моменты

1. Не забудьте *дату* — это в это воскресенье, а не в субботу (мы тоже хотим сходить на ITGM!)
2. Не забудьте *ноутбук* — без него будет скучновато :)
3. Не забудьте *оставить комментарий*, а так же не постесняться написать, если есть какие-то вопросы.

## Для тех, кто хочет прийти в первый раз

Нодскул — это мероприятие, куда мы приходим учиться. Нет каких-то обязательных знаний, чтобы прийти (но вам понадобится ноутбук с зарядкой). Менторы будут помогать, если у вас возникнут какие-то вопросы — не стесняйтесь просить о помощи, ведь мы **ради этого и собрались**. Если что, со мной можно связаться по телеграму: https://t.me/marinintim, и по телефону: +7 921 64 17 256.

До встречи в это воскресенье!

**Comment by Nesterrr** [comment]
:octocat:

**Comment by smirina** [comment]
:octocat:

**Comment by vforvova** [comment]
:octocat:

**Comment by mike1pol** [comment]
@marinintim постараюсь присутствовать

**Comment by vitalyq** [comment]
:octocat:

**Comment by Gurylev** [comment]
@marinintim нафига октокэт?

**Comment by loalexandra** [comment]
:octocat:

**Comment by marinintim** [comment]
@Gurylev: больше октокэтов богу октокэтов! :octocat: :octopus: :100:

**Comment by XeL077** [comment]
:octocat:

**Comment by inkerinmaa** [comment]
:octocat:

**Comment by darinamandarina** [comment]
:octocat:

**Comment by nikitinskaya** [comment]
:octocat:

**Comment by Seminioni** [comment]
:octocat:

**Comment by Dan-Ste** [comment]
:octocat:

**Comment by choibalsan** [comment]
:octocat:

**Comment by pavletto** [comment]
:octocat:

**Comment by chalexIAC** [comment]
:octocat:

**Comment by daniilperestoronin** [comment]
:octocat:

**Comment by loki86** [comment]
:octocat:

**Comment by SuperSurok** [comment]
:octocat:

**Comment by yvinokurov** [comment]
:octocat:

**Comment by bezrukov** [comment]
:octocat:

**Comment by Gurylev** [comment]
:octocat: как в старые-добрые...

**Comment by KIRILLVASILEVICH** [comment]
:octocat:

**Comment by kot91ivan** [comment]
(:octocat:)

**Comment by ORusak** [comment]
:octocat:

**Comment by nikolay-govorov** [comment]
:octocat:

**Comment by alexey-pd** [comment]
:octocat: 💯

**Comment by JuliaVolkova** [comment]
:octocat:

**Comment by devVyacheslav** [comment]
:octocat: 👍

**Comment by dmtoch** [comment]
:octocat:

**Comment by DariusNorv** [comment]
:octocat:

**Comment by ktshrrs** [comment]
(:octocat:)

**Comment by nucleartux** [comment]
:octocat: 💥

**Comment by INesterov** [comment]
:octocat:

**Comment by CKutsenko** [comment]
:octocat:

**Comment by grin7728** [comment]
:octocat:

**Comment by Krerg** [comment]
:octocat:

**Comment by mike1pol** [comment]
:octocat:

**Comment by KulakovSerg** [comment]
:octocat: (мне пофиг остались там места или нет, я просто прийду)

**Comment by nucleartux** [comment]
воркшопы, как всегда :) тут подробнее https://nodeschool.io/ru/

**Comment by ArtemeeSenin** [comment]
:octocat:

**Comment by KulakovSerg** [comment]
> воркшопы, как всегда :) тут подробнее https://nodeschool.io/ru/
а кодревью можно? А то я там что-то написал на ноде, вдруг на прод выльют мою стыдобу...

**Comment by Gurylev** [comment]
> а кодревью можно?
да можно, чё нет-то) надеюсь, там не 20000 строк)

**Comment by katia-trifonova** [comment]
:octocat:

**Comment by adsurov** [comment]
:octocat:

**Comment by s-kobets** [comment]
:octocat:

**Comment by santiago26** [comment]
:octocat:

**Comment by marinintim** [comment]
Спасибо всем, кто пришёл!

Получилось, как мне кажется, хорошо. У нас не было выделенного фотографа, но я что-то успел снять — чуть позже выложу в группу ВК.
