### ISSUE TITLE
13 января 2018 года; Wrike (Свердловская набережная, 44Д)

### ISSUE THREAD

**Issue by Gurylev** [nodeschool/spb#63]
Привет! После небольшого перерыва, двадцать первый нодскул будет 13 января в Wrike.

### Регистрация закрыта

Чтобы попасть на нодскул, вы должны быть зарегистрированы.
С собой нужно взять ноутбук для кодинга, и паспорт/права для преодоления охраны. 

<details>
<summary>Что такое нодскул?</summary>

Нодскул — это ежемесячное оффлайн-мероприятие, где участники проходят [уроки](https://nodeschool.io/#workshoppers) с авто-проверками и могут задать вопросы по коду уроков опытным кодерам. Эти воркшопы (так мы называем такие уроки) помогают изучить JavaScript на фронтенде и бекенде от самых азов до сложных тонкостей фреймворков и библиотек, а также многие другие фронтендерские технологии, без которых в реальной разработке никак.

</details>

<details>
<summary>Что можно узнать на нодскуле?</summary>

На нодскуле можно узнать

* [как](https://github.com/stevekane/promise-it-wont-hurt) [писать](https://github.com/domenic/count-to-6) [современный](https://github.com/isRuslan/learn-generators) [JavaScript](https://github.com/jesstelford/esnext-generation)
* как разобраться в [прототипном](https://github.com/sporto/planetproto) и в [функциональном](https://github.com/timoxley/functional-javascript-workshop) программировании
* и как отличить [лучшие практики написания чистого JS](https://github.com/excellalabs/js-best-practices-workshopper)
* как упростить жизнь [библиотеками](https://github.com/mdunisch/lololodash)
* как [отлаживать](https://github.com/othiym23/bug-clinic) ваш код
* как написать [первые тесты](https://github.com/finnp/test-anything)
* как изучить [азы](https://github.com/workshopper/learnyoureact) и [философию](https://github.com/asbjornenge/thinking-in-react) React
* как упростить работу со стилями при помощи [sass](https://github.com/workshopper/learn-sass) или [less](https://github.com/gnerkus/less-is-more)
* как запилить сайт на [Express](https://github.com/azat-co/expressworks), [Hapi](https://github.com/hapijs/makemehapi) или [Koa](https://github.com/koajs/kick-off-koa)
* как и где хранить данные для ваших приложений ([mongo](https://github.com/evanlucas/learnyoumongo), [counchDB](https://github.com/robertkowalski/learnyoucouchdb), [levelDB](https://github.com/workshopper/levelmeup))
* как превратить сайт в кроссплатформенное приложение на [Electron](https://github.com/maxogden/elementary-electron)
* как работать с [бинарными данными](https://www.github.com/maxogden/bytewiser), [графикой](https://github.com/gl-modules/shader-school) и [аудио](https://github.com/mmckegg/web-audio-school)

</details>

### Приходите 😉
🗺 **Адрес**: Свердловская набережная, 44Д. Карта кликабельна.
🕓 **Дата и время**: 13 января (суббота!) с 14 до 18 часов (4 часа)
⛑ **Менторы**: @Gurylev, @marinintim, @smirina, @vforvova, @bmsdave, @mike1pol 
<figure>
<a href="https://yandex.ru/maps/-/C6EpyMIl"><img width="668" alt="NodeSchool Spb в Wrike по адресу Свердловская набережная, 44Д" src="http://grlv.ru/i/nodeschool-map-15.04.2017.jpg"></a>
<figcaption>

### Будьте готовы 💻
Желательно заранее установить [Node.js](https://nodejs.org/) и [Git Bash](https://git-scm.com/), но если что —  мы поможем уже на мероприятии. Хорошо бы выбрать [воркшоп](https://nodeschool.io/#workshoppers) для прохождения заранее. С собой обязательно нужно взять ноутбук для кодинга и паспорт, чтоб пройти охрану БЦ Лето.

### Для тех, кто первый раз 🦄
Нодскул — это мероприятие, куда мы приходим учиться. Нет каких-то обязательных знаний, чтобы прийти (но вам понадобится ноутбук с зарядкой). Менторы будут помогать, если у вас возникнут какие-то вопросы — не стесняйтесь просить о помощи, ведь мы **ради этого и собрались**. Если что, со мной можно связаться [в телеграме](https://t.me/fogrew).

### Будьте в курсе 🔔
Подписывайтесь на наш календарь ([html](https://vk.cc/6W3ER2), [ical](https://vk.cc/6W3EWR)), там анонс раньше даже, чем на гитхабе.
Подписывайтесь на наши инфо-каналы [в телеграме](https://t.me/nodeschoolspb), [вконтакте](https://vk.com/nodeschoolspb) и [в твиттере](https://twitter.com/nodeschoolspb).
Приходите общаться в нашу [флудилку в телеграме](https://t.me/nodeschoolspb_group).

Приходите изучать ноду и реакт, задавать вопросы, знакомиться, кушать пиццу и пить чай.

----
Здесь в комментариях можно задать любые вопросы по мероприятию.
[Если привыкли](https://github.com/nodeschool/spb/issues/62#issuecomment-339018417), оставьте ещё октокота :octocat: 
До встречи!

**Comment by alexey-pd** [comment]
🐙

**Comment by grin7728** [comment]
+

**Comment by alexandraleo** [comment]
:octocat:

**Comment by bokcart** [comment]
:octocat:

**Comment by mike1pol** [comment]
:octocat:

**Comment by chalexIAC** [comment]
:octocat:

**Comment by kalininilya** [comment]
:octocat:

**Comment by loki86** [comment]
:octocat:

**Comment by AndyVasilev** [comment]
:octocat:

**Comment by Krerg** [comment]
:octocat:

**Comment by JuliaVolkova** [comment]
:octocat:

**Comment by kot91ivan** [comment]
:octocat:

**Comment by SGKuksov** [comment]
:octocat:

**Comment by belozerskiy** [comment]
:octocat:

**Comment by Gurylev** [comment]
Завтра в полдень регистрация закроется.
Если не успеете, пишите мне в [телеграм](https://t.me/fogrew).

**Comment by Gurylev** [comment]
Регистрация закрыта.

**Comment by Gurylev** [comment]
Спасибо всем, что пришли в субботу!

Мы перестали собирать фидбэк, который заполнялся от руки.
Если хочешь оставить честный отзыв о прошедшем нодскуле — пиши в своих социалках с упоминанием @nodeschoolspb. Так мы сможем оставить ссылку на отзыв на нашем сайте.


Подписывайтесь на наш календарь ([html](https://vk.cc/6W3ER2), [ical](https://vk.cc/6W3EWR)), информационные каналы [в телеграме](https://t.me/nodeschoolspb), [вконтакте](https://vk.com/nodeschoolspb) и [в твиттере](https://twitter.com/nodeschoolspb), оттуда вы узнаете информацию о февральском нодскуле.
Приходите общаться и задавать вопросы в чаты во [флудилку в телеграме](https://t.me/nodeschoolspb_group).
