### ISSUE TITLE
17 февраля 2018 года; Одноклассники (ул. Херсонская 12-14, БЦ «Ренессанс Правда»)

### ISSUE THREAD

**Issue by Gurylev** [nodeschool/spb#64]
Привет, котаны! 😸 Ждите следующий нодскул в середине февраля: 17 числа.

Возможно, мы решимся поэкспериментировать с форматом
и сделаем мастер-класс. Но это не точно.

### Регистрация закрыта

Чтобы попасть на нодскул, нужно быть зарегистрированным. Иначе вы не пройдёте охрану.

<details>
<summary>Что такое нодскул?</summary>

Нодскул — это ежемесячное оффлайн-мероприятие, где участники проходят [уроки](https://nodeschool.io/#workshoppers) с авто-проверками и могут задать вопросы по коду уроков опытным кодерам. Эти воркшопы (так мы называем такие уроки) помогают изучить JavaScript на фронтенде и бекенде от самых азов до сложных тонкостей фреймворков и библиотек, а также многие другие фронтендерские технологии, без которых в реальной разработке никак.

</details>

<details>
<summary>Что можно узнать на нодскуле?</summary>

На нодскуле можно узнать

* [как](https://github.com/stevekane/promise-it-wont-hurt) [писать](https://github.com/domenic/count-to-6) [современный](https://github.com/isRuslan/learn-generators) [JavaScript](https://github.com/jesstelford/esnext-generation)
* как разобраться в [прототипном](https://github.com/sporto/planetproto) и в [функциональном](https://github.com/timoxley/functional-javascript-workshop) программировании
* и как отличить [лучшие практики написания чистого JS](https://github.com/excellalabs/js-best-practices-workshopper)
* как упростить жизнь [библиотеками](https://github.com/mdunisch/lololodash)
* как [отлаживать](https://github.com/othiym23/bug-clinic) ваш код
* как написать [первые тесты](https://github.com/finnp/test-anything)
* как изучить [азы](https://github.com/workshopper/learnyoureact) и [философию](https://github.com/asbjornenge/thinking-in-react) React
* как упростить работу со стилями при помощи [sass](https://github.com/workshopper/learn-sass) или [less](https://github.com/gnerkus/less-is-more)
* как запилить сайт на [Express](https://github.com/azat-co/expressworks), [Hapi](https://github.com/hapijs/makemehapi) или [Koa](https://github.com/koajs/kick-off-koa)
* как и где хранить данные для ваших приложений ([mongo](https://github.com/evanlucas/learnyoumongo), [counchDB](https://github.com/robertkowalski/learnyoucouchdb), [levelDB](https://github.com/workshopper/levelmeup))
* как превратить сайт в кроссплатформенное приложение на [Electron](https://github.com/maxogden/elementary-electron)
* как работать с [бинарными данными](https://www.github.com/maxogden/bytewiser), [графикой](https://github.com/gl-modules/shader-school) и [аудио](https://github.com/mmckegg/web-audio-school)

</details>

### Приходите 😉
🗺 **Адрес**: ул. Херсонская 12-14, БЦ «Ренессанс Правда», 8 этаж, офис «Одноклассники».
🕓 **Дата и время**: 17 февраля (суббота!) с 14 до 18 часов (4 часа)
⛑ **Менторы**: @Gurylev, @marinintim, @bmsdave, @mike1pol, @zeckson, @nucleartux, @scink, @alexey-pd
<figure>
<a href="https://yandex.ru/maps/-/C6BLIF46"><img width="600" height="450" alt="NodeSchool Spb в OK.ru по адресу ул. Херсонская 12-14" src="https://static-maps.yandex.ru/1.x/?l=map&lang=ru_RU&ll=30.379125217406937%2C59.92810030924567&origin=jsapi-constructor&pt=30.381005%2C59.928654%2Cpm2bll&size=600%2C450&z=15"></a>
<figcaption>

### Будьте готовы 💻
Желательно заранее установить [Node.js](https://nodejs.org/) и [Git Bash](https://git-scm.com/), но если что —  мы поможем уже на мероприятии. Хорошо бы выбрать [воркшоп](https://nodeschool.io/#workshoppers) для прохождения заранее. С собой обязательно нужно взять ноутбук для кодинга и паспорт, чтоб пройти охрану БЦ «Ренессанс Правда».

### Для тех, кто первый раз 🦄
Нодскул — это мероприятие, куда мы приходим учиться. Нет каких-то обязательных знаний, чтобы прийти (но вам понадобится ноутбук с зарядкой). Ксли у вас возникнут какие-то вопросы — не стесняйтесь просить о помощи, ведь мы **ради этого и собрались**.  Менторы помогут.

### Будьте в курсе 🔔
Подписывайтесь на наш календарь ([html](https://vk.cc/6W3ER2), [ical](https://vk.cc/6W3EWR)), там анонс раньше даже, чем на гитхабе.
Подписывайтесь на наши инфо-каналы [в телеграме](https://t.me/nodeschoolspb), [вконтакте](https://vk.com/nodeschoolspb) и [в твиттере](https://twitter.com/nodeschoolspb).
Приходите общаться в нашу [флудилку в телеграме](https://t.me/nodeschoolspb_group).

Приходите изучать ноду и реакт, задавать вопросы, знакомиться, кушать пиццу и пить чай.

----
Здесь в комментариях можно задать любые вопросы по мероприятию.
[Если привыкли](https://github.com/nodeschool/spb/issues/62#issuecomment-339018417), оставьте ещё октокота :octocat: 
До встречи!

**Comment by alexey-pd** [comment]
🐙

**Comment by nikolay-govorov** [comment]
:octocat:

**Comment by plonina** [comment]
:octocat:

**Comment by personaljs** [comment]
:octocat:

**Comment by kot91ivan** [comment]
:octocat:

**Comment by alexandraleo** [comment]
:octocat:

**Comment by ORusak** [comment]
:octocat:

**Comment by luxeon89** [comment]
:octocat:

**Comment by loki86** [comment]
:octocat:

**Comment by s-ilya** [comment]
:octocat:

**Comment by karachev** [comment]
![image](https://user-images.githubusercontent.com/10108642/35270772-24740c8a-0041-11e8-9a43-fdfa7a3d4886.png)

**Comment by dsdolzhenko** [comment]
:octocat:

**Comment by thepocp** [comment]
:octocat:

**Comment by SuperSurok** [comment]
:octocat:

**Comment by chalexIAC** [comment]
:octocat:

**Comment by katasup** [comment]
:octocat:

**Comment by Seminioni** [comment]
:octocat:

**Comment by livevasiliy** [comment]
:octocat:

**Comment by Maxvgrad** [comment]
:octocat:

**Comment by pepelsbey** [comment]
:octocat:

**Comment by terdenan** [comment]
:octocat:

**Comment by DmitryVengerov** [comment]
:octocat:

**Comment by gkvodopad2** [comment]
:octocat:

**Comment by gkvodopad** [comment]
:octocat:

**Comment by alekskond** [comment]
:octocat:

**Comment by belozerskiy** [comment]
:octocat:

**Comment by Gurylev** [comment]
Регистрация закрыта!
Я не знаю, почему некоторые отметились на гитхабе, но не зарегистрировались в форме (сейчас ссылку на форму я уже убрал, чтоб никого не путать).
Я подаю списки с именами и фамилиями на охрану бизнес-центра. В этом же списке вам нужно будет найти себя на входе. Не имея ваших имени и фамилии, я не могу их передать, а значит вас не пропустят.
Сейчас оставили здесь комментарий, но не зарегистрировались:
@alekskond @gkvodopad2 @terdenan @Seminioni @katasup @kot91ivan @personaljs 
Если вы в этом списке ↑ и действительно хотите прийти — пишите мне [в телеграм](https://t.me/fogrew).

**Comment by Gurylev** [comment]
Спасибо всем, что пришли в субботу!

Если хотите оставить честный отзыв о прошедшем нодскуле — пишите в своих социалках с упоминанием @nodeschoolspb. Так мы сможем оставить ссылку на отзыв на нашем сайте. Или можете заполнить [форму обратной связи](https://goo.gl/forms/iQ25PYIdCXEUu0xf2). Это поможет нам улучшить нодскул в будущем.

Подписывайтесь на наш календарь ([html](https://vk.cc/6W3ER2), [ical](https://vk.cc/6W3EWR)), информационные каналы [в телеграме](https://t.me/nodeschoolspb), [вконтакте](https://vk.com/nodeschoolspb) и [в твиттере](https://twitter.com/nodeschoolspb), оттуда вы узнаете информацию о будущих встречах нашего сообщества.
Приходите общаться и задавать вопросы в чаты во [флудилку в телеграме](https://t.me/nodeschoolspb_group).

До встречи!
