### ISSUE TITLE
24 марта 2018 года; PlayKot (Кропоткина, 1) БЦ «Сенатор» 7 этаж

### ISSUE THREAD

**Issue by smirina** [nodeschool/spb#65]
Привет!

Мы решились попробовать новый формат и открываем регистрацию на маленький мартовский нодскул. 
___Регистрация закрыта!___

**Что за формат?** Аудитория поделится на две части? Кроме прохождения воркшопов можно будет под руководством @mike1pol написать свой блог на nodejs / React / GraphQL. В каждую из групп мы готовы пригласить всего по 15 человек, так что заранее регистрацию не объявляли.

**Так что там с блогом?**
Это мастер-класс для тех, кто **уже знает** React и Node.js
В программе (попробуем успеть все!):

- Установка глобальных зависимостей
- Инициализация проекта
- Разбор скелета проекта из чего состоит и как работает
- Написание моделей нашего блога
- Пишем простенькую авторизация с auth0
- Пишем policy для нашего приложения
- Пишем веб приложение с использованием graphql
- Авторизация / Регистрация
- Создание / Редактирование поста
- Список постов
- Просмотр поста
- Создаем docker контейнер нашего проекта

🗺 Адрес: ул. Кропоткина д.1, офис «PlayKot» БЦ «Сенатор» 7 этаж.
🕓 Дата и время: 24 марта (суббота!) с 14 до 18 часов (4 часа)
⛑ Менторы: @Gurylev, @marinintim, @mike1pol, @zeckson, @alexey-pd

Будьте готовы 💻
Желательно заранее установить [Node.js](https://nodejs.org/en/) и [Git Bash](https://git-scm.com/), но если что — мы поможем уже на мероприятии. Хорошо бы выбрать [воркшоп](https://nodeschool.io/#workshoppers) для прохождения заранее. С собой обязательно нужно взять ноутбук для кодинга и паспорт, чтоб пройти охрану БЦ .

Будьте в курсе 🔔
Подписывайтесь на наши инфо-каналы в [телеграме](https://t.me/nodeschoolspb), [вконтакте](https://vk.com/nodeschoolspb) и в [твиттере](https://twitter.com/nodeschoolspb).
Приходите общаться в нашу [флудилку в телеграме](https://t.me/nodeschoolspb_group).

Приходите учиться вместе, задавать вопросы, и знакомиться.

Здесь в комментариях можно задать любые вопросы по мероприятию.
Если привыкли, оставьте ещё октокота :octocat:
До встречи!

(Информация актуальна и обновляется)

**Comment by olegk101** [comment]
:octocat:

**Comment by dshved** [comment]
:octocat:

**Comment by SuperSurok** [comment]
:octocat:

**Comment by alexey-pd** [comment]
:octocat:

**Comment by pltnm239** [comment]
:octocat:

**Comment by JuliaVolkova** [comment]
:octocat:

**Comment by Nesterrr** [comment]
:octocat:

**Comment by abelozerov** [comment]
:octocat:

**Comment by MaceEsina** [comment]
:octocat:

**Comment by belozerskiy** [comment]
:octocat:

**Comment by livevasiliy** [comment]
:octocat:

**Comment by devVyacheslav** [comment]
:octocat:

**Comment by babrums** [comment]
:octocat:

**Comment by choibalsan** [comment]
:octocat:

**Comment by sajuryy** [comment]
:octocat:

**Comment by Maxvgrad** [comment]
:octocat:

**Comment by sen4az** [comment]
:octocat:

**Comment by Alexter-progs** [comment]
:octocat:

**Comment by lexantus** [comment]
:octocat:

**Comment by Matthew-Risedale** [comment]
:octocat:
