### ISSUE TITLE
26 мая; Playkot, Кропоткина, 1

### ISSUE THREAD

**Issue by marinintim** [nodeschool/spb#66]
Нежданно-негаданно мы проводим очередной нодскул. Я понимаю, что май был тяжёлый — очень много событий и сложно везде успеть. (на нодскуле можно отдохнуть и просто покодить!) 

**Место**: Playkot, БЦ Сенатор, [Кропоткина, 1](https://yandex.ru/maps/-/CBaOJNgDOC
)
**Время**: 26 мая (эта суббота!), 14:00
**Регистрация**: [Гуглоформа](https://goo.gl/forms/qBIMzqF6qZ4HkDoW2)

Не забудьте принести с собой ноутбук и паспорт.

---

И ни слова про GDPR!

**Comment by Gurylev** [comment]
> на нодскуле можно отдохнуть и просто покодить!
ахах)) как только GDPR доделаю, так сразу!

**Comment by nucleartux** [comment]
🤙

**Comment by Nesterrr** [comment]
:octocat:

**Comment by sajuryy** [comment]
:octocat:
