### ISSUE TITLE
30 июня 2018 года; SEMrush (ул. Заставская, 22А, БЦ МегаПАРК)

### ISSUE THREAD

**Issue by fogrew** [nodeschool/spb#67]
<a href="https://ru.semrush.com/" target="_blank" rel="noopener"><img src="https://seoprofy.ua/wp-content/uploads/2014/03/sem-rush-logo.png" alt="SEMrush logo" align="right" width="120"></a>Следующий нодскул будет в SEMrush 30 июня.

### [Регистрация](https://goo.gl/forms/ZsgzmOQ2hxNDukv22)

🕓 Когда: 30 июня (суббота!) с 14 до 18 часов (4 часа)
🗺 Где: ул. Заставская, 22А, БЦ «МегаПарк», 2 этаж, офис SEMrush
⛑ Менторы: @marinintim, @mike1pol, @zeckson, @nucleartux

<figure>
<a href="http://bit.do/ns24map"><img width="668" height="424" alt="NodeSchool SPb в SEMrush по адресу ул. Заставская 22А" src="https://gurylev.com/i/dg3pus9q73.jpg"></a>
<figcaption>Маршрут от м. Московские ворота до БЦ МегаПарк</figcaption>
</figure>

---
Здесь в комментариях можно задать любые вопросы по мероприятию.
До встречи!

**Comment by yvinokurov** [comment]
:octocat:

**Comment by shaulyn** [comment]
сколько стоит вход?

**Comment by fogrew** [comment]
@shaulyn бесплатно 😉

**Comment by vganshin** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/octocat.png)

**Comment by JuliaVolkova** [comment]
:octocat:

**Comment by Alhxor** [comment]
:octocat:

**Comment by Maxvgrad** [comment]
:octocat:

**Comment by fogrew** [comment]
Хочу всем напомнить, что оставлять здесь октокота не обязательно. Главное - [зарегистрироваться в форме](http://bit.do/nsspb24).
@yvinokurov @vganshin ↑

**Comment by vganshin** [comment]
Понял, спасибо.

**Comment by workAnonim** [comment]
Что такое нодскул и какая главная задача мероприятия?

**Comment by fogrew** [comment]
Регистрация закрыта.
