### ISSUE TITLE
14 июля 2018 года; Epic Skills (Кронверкский пр., 23)

### ISSUE THREAD

**Issue by iwanttobealight** [nodeschool/spb#68]
Следующий нодскул будет в офисе Epic Skills 14 июля.
### [Регистрация](https://goo.gl/PwKove)

:clock2: Когда: 14 июля (суббота!) с 14 до 18 часов (4 часа)
:world_map: Где: Кронверкский проспект, 23, офис Epic Skills
:rescue_worker_helmet: Менторы: @fogrew, @scink, @alexey-pd, @agufranov

[![image](https://camo.githubusercontent.com/b5dfc5aae17589a9a1e85c5656e363957f7a12d5/687474703a2f2f67726c762e72752f692f6e6f64657363686f6f6c2d6d61702d323031372d30332d32352e6a7067)](https://goo.gl/maps/RynBqFWaWEq)

Кронверкский проспект, 23 (Вход через 25-й дом, на воротах *1908#)

**Не забудьте взять ноутбук!**

Здесь в комментариях можно задать любые вопросы по мероприятию.
До встречи!

**Comment by Alhxor** [comment]
:octocat:

**Comment by JuliaVolkova** [comment]
:octocat:

**Comment by marinintim** [comment]
:octocat:

**Comment by RomanFadeev26** [comment]
:octocat:

**Comment by glukki** [comment]
:octocat:

**Comment by asader** [comment]
:octocat:

**Comment by squalsoft** [comment]
:+1:
