### ISSUE TITLE
22 сентября 2018 года; Аркадия (Большой Сампсониевский проспект, 28 корпус 2, БЦ Mezon Plaza)

### ISSUE THREAD

**Issue by iwanttobealight** [nodeschool/spb#70]
Следующий нодскул будет в Аркадии 22 сентября.
### [Регистрация](https://goo.gl/forms/z4Y9nMFKcjfLs5ci1)

:clock2: Когда: 22 сентября (суббота!) с 14 до 18 часов (4 часа)
:world_map: Где: Большой Сампсониевский проспект, 28 корпус 2, БЦ Mezon Plaza, Аркадия
:rescue_worker_helmet: Менторы: @alexey-pd, @nucleartux, @scink

[![image](https://pp.userapi.com/c850136/v850136676/27761/Xc_R4UETL6A.jpg)](https://yandex.ru/maps/-/CBBi64ubCB)

**Не забудь взять паспорт и ноутбук!**

Чтобы не отвлекаться на разговоры, захвати наушники 🎧 

Здесь в комментариях можно задать любые вопросы по мероприятию.
До встречи!

**Comment by luxeon89** [comment]
:octocat:

**Comment by alexey-pd** [comment]
:octocat:
