### ISSUE TITLE
24 ноября 2018 года; EPAM (ул. Заставская, 22А, БЦ МегаПАРК)

### ISSUE THREAD

**Issue by dmorenogogoleva** [nodeschool/spb#73]
Следующий нодскул будет в EPAM 24 ноября.
:octocat: Задеплоим что-то клёвое! :octocat: 

### [Регистрация](https://goo.gl/forms/P9deCxeq4RzMehvz2)

В этот раз нас ждёт воркшоп **«Небольшой продакшен: как деплоить приложение на Node.js»** от  [Тима Маринина](https://github.com/marinintim)

🎬  Когда: 24 ноября (суббота!) с 14 до 18 часов (4 часа)
🔍  Где: ул. Заставская, 22А, БЦ МегаПАРК, офис EPAM
📟  Менторы: @marinintim, @alexey-pd, @scink, @Matthew-Risedale

В ходе воркшопа участники узнают на своём опыте, что такое VPS, и задеплоят (уже готовое) приложение на ноде на сервер, разберутся, как сделать так, чтобы оно перезапускалось в случае ошибок, как выкатывать новые версии приложения, немного поговорим о логах.

На воркшопе будет рассмотрен один из самых простых вариантов деплоя, который подойдёт несложным приложениям, которым хватит мощности одного сервера.

[![image](https://pp.userapi.com/c846524/v846524046/11bd78/lpd-dQov6ko.jpg)](https://yandex.ru/maps/-/CBBTrMwKxB)

**Не забудь взять паспорт и ноутбук!**

Нодскул длится четыре часа, обязательно позавтракай 🍏
Чтобы не отвлекаться на разговоры, захвати наушники 🎧

Здесь в комментариях можно задать любые вопросы по мероприятию.
До встречи!
:octocat:

**Comment by dmorenogogoleva** [comment]
🎸 🔥 🏍

**Comment by Diligens** [comment]
:octocat: 💚

**Comment by agrogov** [comment]
Как называется этот воркшоп в списке воркшопов на форме регистрации?

**Comment by ORusak** [comment]
:octocat:

**Comment by sergeigavrish** [comment]
ого, уже билетов нет. жизнь жестока(

**Comment by dmorenogogoleva** [comment]
> ого, уже билетов нет. жизнь жестока(

приходи в следующем году!

**Comment by dmorenogogoleva** [comment]
> Как называется этот воркшоп в списке воркшопов на форме регистрации?

никак)
он вне списков

**Comment by Krerg** [comment]
Весь нодскул (4 часа) будем делать этот воркшоп? Или можно взять другой?

**Comment by nucleartux** [comment]
> Весь нодскул (4 часа) будем делать этот воркшоп? Или можно взять другой?

Да, все 4 часа. Да, можно взять другой.
