### ISSUE TITLE
27 января 2019 года; Одноклассники (ул. Херсонская 12-14, БЦ «Ренессанс Правда»)

### ISSUE THREAD

**Issue by dmorenogogoleva** [nodeschool/spb#74]
Следующий нодскул пройдет в «Одноклассниках» 27 января.
### [Регистрация](https://goo.gl/forms/6gjZMOsURiCaTD1A3)

:clock2: Когда: 27 января (воскресенье!) с 14 до 18 часов (4 часа)
:world_map: Где:  ул. Херсонская 12-14, БЦ «Ренессанс Правда», 8 этаж, офис «Одноклассники»
:rescue_worker_helmet: Менторы: @marinintim, @alexey-pd, @scink, @bmsdave

[![image](https://pp.userapi.com/c849428/v849428599/f1e02/fDpfV0SEn30.jpg)](https://yandex.ru/maps/-/CBRyBWWltA)

**Не забудьте взять наушники, паспорт и ноутбук!**

Здесь в комментариях можно задать любые вопросы по мероприятию.
До встречи!

**Comment by dmorenogogoleva** [comment]
:octocat:

**Comment by gucol** [comment]
:octocat:

**Comment by dmitrylebedev** [comment]
:octocat: 

@iwanttobealight, 27 января - воскресенье

**Comment by lksei** [comment]
:octocat:

**Comment by dmorenogogoleva** [comment]
> :octocat:
> 
> @iwanttobealight, 27 января - воскресенье

а ведь ты прав!

**Comment by Quoiaaaaa** [comment]
+

**Comment by rooless** [comment]
А трансляции не будет?

**Comment by dragin96** [comment]
когда подтвердят, что мы попали на мероприятие?
с другого города едем просто

**Comment by Margino** [comment]
:octocat:

**Comment by rivestone** [comment]
:octocat:

**Comment by bw31** [comment]
:octocat:

**Comment by Alex-Chernv** [comment]
:octocat:

**Comment by dmorenogogoleva** [comment]
> когда подтвердят, что мы попали на мероприятие?
> с другого города едем просто

должно было прийти письмо на почту

если не пришло — напишите в чат https://t.me/nodeschoolspb_group

**Comment by dmorenogogoleva** [comment]
> А трансляции не будет?

к сожалению не будет 🦑

**Comment by Margino** [comment]
> > когда подтвердят, что мы попали на мероприятие?
> > с другого города едем просто
> 
> должно было прийти письмо на почту
> 
> если не пришло — напишите в чат https://t.me/nodeschoolspb_group

А что ещё письмо должно придти?

**Comment by dmorenogogoleva** [comment]
> > > когда подтвердят, что мы попали на мероприятие?
> > > с другого города едем просто
> > 
> > 
> > должно было прийти письмо на почту
> > если не пришло — напишите в чат https://t.me/nodeschoolspb_group
> 
> А что ещё письмо должно придти?

должно, но если не пришло, напишите ваши ФИО в чат https://t.me/nodeschoolspb_group и мы проверим вручную

**Comment by Margino** [comment]
> > > > когда подтвердят, что мы попали на мероприятие?
> > > > с другого города едем просто
> > > 
> > > 
> > > должно было прийти письмо на почту
> > > если не пришло — напишите в чат https://t.me/nodeschoolspb_group
> > 
> > 
> > А что ещё письмо должно придти?
> 
> должно, но если не пришло, напишите ваши ФИО в чат https://t.me/nodeschoolspb_group и мы проверим вручную

Спасибо, разобрался. Только сейчас понял, что заголовок «Регистрация» — это ссылка.
