### ISSUE TITLE
30 марта 2019 года; T-Systems (13-линия В.О., д.14)

### ISSUE THREAD

**Issue by dmorenogogoleva** [nodeschool/spb#76]
Следующий нодскул будет в офисе T-Systems 30 марта.

# [Зарегистрироваться](https://goo.gl/forms/AkTO5a9YxDIzKJuC3)

🕑 Когда: 30 марта (суббота!) с 14 до 18 часов (4 часа)
🗺 Где: 13-линия В.О., д.14 БЦ «Елизаветинский», вход в голубое здание, 3 этаж, офис T-Systems
🌵Менторы: @marinintim, @alexey-pd, @scink, @nucleartux

[![image](https://sun9-2.userapi.com/c830400/v830400041/167d1b/x_BPFFdhpNk.jpg)](https://yandex.ru/maps/-/CBQAJPabcD)

**Не забудьте взять наушники, паспорт и ноутбук!**

Здесь в комментариях можно задать любые вопросы по мероприятию.
До встречи!

**Comment by dmorenogogoleva** [comment]
:octocat: 🔥

**Comment by Seminioni** [comment]
:octocat:

**Comment by Quoiaaaaa** [comment]
+

**Comment by nucleartux** [comment]
🚶

**Comment by SergeySherstnev** [comment]
И как регистрироваться на мероприятие?

**Comment by nikitagolubitskiy** [comment]
@SergeySherstnev, в первом комменте ссылка на форму регистрации - [Зарегистрироваться](https://goo.gl/forms/AkTO5a9YxDIzKJuC3)

**Comment by lksei** [comment]
⚡️

**Comment by nucleartux** [comment]
@SergeySherstnev  
![Screenshot 2019-03-13 at 13 36 52](https://user-images.githubusercontent.com/199706/54272770-61841300-4595-11e9-98f8-b22af17bf2e0.png)
