### ISSUE TITLE
27 апреля 2019 года; DataArt (Большой Сампсониевский, 60А)

### ISSUE THREAD

**Issue by dmorenogogoleva** [nodeschool/spb#77]
Следующий нодскул пройдёт в офисе DataArt 27 апреля

# [Зарегистрироваться](https://forms.gle/2XbdpRjrjCAzSPpF7)

⏳Когда: 27 апреля (суббота!) с 14 до 18 часов (4 часа)
🌍Где: Большой Сампсониевский, 60А. Вход в бизнес-центр со стороны Гельсингфорсской улицы, 4  — в подъезд с табличкой «Телеком СПб», офис DataArt
🍸Менторы: @marinintim, @alexey-pd, @scink

[![image](https://pp.userapi.com/c848636/v848636269/16931e/PZMHE2hviP4.jpg)](https://yandex.ru/maps/-/CCB65Yiv)

**Не забудьте взять наушники, паспорт и ноутбук!**

Здесь в комментариях можно задать любые вопросы по мероприятию.
До встречи!

**Comment by dmorenogogoleva** [comment]
:octocat:

**Comment by lksei** [comment]
:octocat:

**Comment by likeavenus** [comment]
Какой воркшоп указать при регистрации?

**Comment by dmorenogogoleva** [comment]
> Какой воркшоп указать при регистрации?

тот который планируете проходить
на мероприятии можно будет передумать

**Comment by KosenkovRuslan** [comment]
Добрый день, будет где ноутбук к розетке подключить?(мало времени держит заряд)

**Comment by lksei** [comment]
> Добрый день, будет где ноутбук к розетке подключить?(мало времени держит заряд)

розетки будут доступны

**Comment by KosenkovRuslan** [comment]
Спасибо
