### ISSUE TITLE
27 октября 2019 года; СКБ Контур (Большая Пушкарская ул. 22)

### ISSUE THREAD

**Issue by dmorenogogoleva** [nodeschool/spb#78]
Следующий нодскул будет в Контуре 27 октября.
### [Регистрация](https://forms.gle/aBXcMNNZJQ73EKcE6)

:clock2: Когда: 27 октября (воскресенье!) с 14 до 18 часов (4 часа)
:world_map: Где: Большая Пушкарская ул. 22, БЦ Сенатор, СКБ Контур
🛍 Что взять с собой: ноутбук и паспорт
🦉 Менторы: @marinintim, @alexey-pd

#
[![image](https://pp.userapi.com/c852132/v852132106/14840/CghTiuyi788.jpg)](https://yandex.ru/maps/-/CBBjAWhZSC)

Нодскул длится четыре часа, обязательно позавтракай 🍏🍎
Чтобы не отвлекаться на разговоры, захвати наушники 🎧

**Не забудь паспорт и ноутбук!**

Здесь в комментариях можно задать любые вопросы по мероприятию.
До встречи!
:octocat:

**Comment by Mikman83** [comment]
27 октября 2019 года?
 это будет  воскресенье.
 и да, как зарегаться?)

**Comment by volkova-annie** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSdapOC-ICN6hHLFhRzQoURlPRGQ8cguwDA3KJcniaCwgwj9Ww/viewform

Там ссылка, где текст "Регистрация"

**Comment by Mikman83** [comment]
благодарю.

**Comment by lksei** [comment]
:octocat:

**Comment by dmorenogogoleva** [comment]
> 27 октября 2019 года?
> это будет воскресенье.
> и да, как зарегаться?)

Это будет в воскресенье!

Регистрация по ссылке https://forms.gle/aBXcMNNZJQ73EKcE6

**Comment by Mikman83** [comment]
спасибо!

**Comment by kolebayev** [comment]
Привет. В разделе 'Какой воркшоп планируете пройти в этот раз?' в гугл формах не работает ссылка [списка воркшопов](https://nodeschool.io/#workshopper-list). Из селекта плохо понятно что выбрать, подскажите где можно почитать подробно. Спасибо

**Comment by lksei** [comment]
@kolebayev в начале мероприятия будет презентация и ссылки. 

всегда можно начать с `javascripting` или `learnyounode`

**Comment by seregaed** [comment]
Есть розетка для ноута без батареи? )
