### ISSUE TITLE
29 февраля 2020 года; Одноклассники (ул. Херсонская 12-14, БЦ «Ренессанс Правда»)

### ISSUE THREAD

**Issue by dmorenogogoleva** [nodeschool/spb#79]
Следующий нодскул пройдет в «Одноклассниках» 29 февраля
### [Регистрация](https://forms.gle/4NSoZS6FPpazEbF27)

:clock2: Когда: 29 февраля (суббота!) с 14 до 18 часов (4 часа)
:world_map: Где:  ул. Херсонская 12-14, БЦ «Ренессанс Правда», 8 этаж, офис «Одноклассники»
🐍 Менторы: @marinintim, @alexey-pd, @bmsdave

[![image](https://sun9-50.userapi.com/c200816/v200816610/4b9d8/n93HAYZFf-I.jpg)](https://yandex.ru/maps/-/CBRyBWWltA)

**Не забудьте взять наушники, паспорт и ноутбук!**

Здесь в комментариях можно задать любые вопросы по мероприятию.
До встречи!

**Comment by ghost** [comment]
Привет! Нужно ли регистрироваться? Для совсем зеленых новичков в вебе подойдет школа?

**Comment by romant094** [comment]
А есть программа? Что будет на мероприятии?

**Comment by lksei** [comment]
@PonikarovaV заполняем форму чтобы были места и охрана пропустила, задания разной сложности в том числе для новичков

**Comment by lksei** [comment]
> А есть программа? Что будет на мероприятии?

в начале презентация, далее работа над заданиями общение (точно) и пицца (возможно)

**Comment by ghost** [comment]
Извиняюсь, большие синие буквы не увидела ))

**Comment by m1khaylov** [comment]
:octocat:

**Comment by lksei** [comment]
:1234:

**Comment by terdenan** [comment]
:octocat:

**Comment by apetrovskiy** [comment]
код воркшопа какой? learnyounode?

**Comment by lksei** [comment]
> код воркшопа какой? learnyounode?

Например, но можно и позже решить

**Comment by dmrnz** [comment]
:octocat:
