### ISSUE TITLE
Новый логотип

### ISSUE THREAD

**Issue by marinintim** [nodeschool/spb#8]
Сейчас у нас логотип стандартный, а хочется какой-то связанный с Петербургом.

Нужен векторный шестиугольник, то есть формат тот же.

Тогда можно будет стикеры смело печатать.

**Comment by Gurylev** [comment]
аххахах, принимайте. Это лишь идея, корабль лучше более детализированный нагуглить)
![Ahahahaha]
(http://grlv.ru/files/nodeschool.svg)

**Comment by ipelekhan** [comment]
Охлол :)
Не, давайте в стиле Осаки или Берлина, можно посмотреть на
http://nodeschool.io/hexdex.html

**Comment by Gurylev** [comment]
А что изобразить? Ростральные колонны? Петропавловская крепость? Александрийский столп и Дворцовую площадь? Медного всадника?
Разводные мосты беспонтово смотрятся.

**Comment by marinintim** [comment]
Меднай всадник более менее однозначно, а остальное могут и не распарсить.

**Comment by ipelekhan** [comment]
Либо "гречу, парадную, шаверму, а вокруг всё в поребриках" :-)

**Comment by Gurylev** [comment]
Ограничил Петра шестиугольником. Два варианта набросал, отличается только цветовая гамма. К использованию ещё не готово, нужно оптимизировать точки и вес файла. Что скажете? 

![Peter]
(http://grlv.ru/files/node.svg)
![Peter Dark]
(http://grlv.ru/files/node-dark.svg)

**Comment by Gurylev** [comment]
Мне кажется, на всех логотипах nodeschool не хватает логотипа ноды :cat:

**Comment by ipelekhan** [comment]
Офигенно! Цветовую гамму можно попробовать Зенитовскую, только слегка
приглушить цвета.

По поводу логотипа ноды -- шестиугольник же!

**Comment by ipelekhan** [comment]
@Gurylev посмотрел на нормальном мониторе, второй вариант лучше всего, где граница и постамент с фигурой одного цвета. Надпись nodeschool может быть немного сдвинуть налево. По поводу веса файла не заморачивайся -- экспортируй в svg и делай pull request на master ветку.

Надо будет подумать над стикерами. Спонсоров у нас нет, краудфандинг бы сильно выручил :-)

**Comment by ipelekhan** [comment]
![nodeschool spb](https://cloud.githubusercontent.com/assets/2616427/8084528/1bee55b6-0f94-11e5-864b-b0e0d64b8137.png)

Ну кароч больше приглушенного темно синего. Так-то конечно Питер -- это серятина, согласен ;-)

* И тут я понял, что монитор не откаллиброван.

**Comment by ipelekhan** [comment]
Надпись NODESCHOOL нужно чем-то уравновесить. На отредактированном мною варианте она типа по центру и слегка сдвинута наверх, чтобы не так адово было. Можно дописать римскими цифрами год где-нибудь ниже: MMXV.

* У меня есть знакомый дизайнер, который правда по полиграфии больше, могу попросить её, рисовать она точно не будет, но сдвинуть надписи и прикольные цвета подобрать согласится.

**Comment by Gurylev** [comment]
NodeSchool spb дальше 2015 не будет жить? Зачем там год?

**Comment by ipelekhan** [comment]
На Медном Всаднике написан год основания :wink:

Но про год была только идея. Может быть ничего и не надо.

**Comment by vkfont** [comment]
сам по себе логотип нужен только чтобы лепить его на ноутбуки (имхо)
в таком случае год жизненно необходим - с ним легче объяснить почему на ноутбуке две одинаковых наклейки: года-то разные :)

**Comment by ipelekhan** [comment]
@vkfont Ты не узнал Петра Первого на коне? :smirk: 

Хотя есть логика по поводу здания. Всё таки школа обычно внутри здания находится, а не памятника :wink:

**Comment by Gurylev** [comment]
@vkfont Я предлагал выше варианты. Выберите или предложите что-то более известное. И что хоть как-то можно изобразить в векторе, чтоб оно было узнаваемым. Попробуем.

**Comment by marinintim** [comment]
@Gurylev мне нравится всадник.

**Comment by marinintim** [comment]
Взяли синего пока. Придумаем менять — откроем ещё одну ишью.
