### ISSUE TITLE
4 июля 2020 года; онлайн

### ISSUE THREAD

**Issue by dmorenogogoleva** [nodeschool/spb#80]
Следующий нодскул пройдет 4-го июля  2020 (суббота) в 14:00 онлайн в формате лекции от @zeckson  

*********************************************************
Ссылка на видео: https://www.youtube.com/watch?v=mV59ZmSHU9Q&feature=youtu.be
Ссылка на презентацию: console@nodeschoolspb.pdf
Ссылка на файлы скриптов из презентации: https://github.com/zeckson/tips-and-tricks/tree/master/shell
*********************************************************

# Краткий курс молодого бойца по консоли

Вы узнаете — чем отличается терминал от интерпретатора и причём тут консоль. Поговорим про синтаксис интерпретаторов в разных операционных системах. Соберём список самых востребованных команд на каждый день, а так же узнаем общий синтаксис и правила работы всех прочих команд. Познакомимся с консольными приложениями (программами) на вашем компьютере и узнаем как они работают. 

Чего не будет:
- подробного анализа работы ОС
- системного администрирования
- безопасности и защиты информации

Для кого будет полезна лекция?
Новички и те, кто хотел бы разобраться как работают консольные приложения.

Вступайте в нашу [флудилку](https://t.me/nodeschoolspb_group), чтобы задавать вопросы во время лекции.

**Comment by deniolp** [comment]
Отличная лекция, Женя! Спасибо!

**Comment by zeckson** [comment]
Ссылка на видео: https://www.youtube.com/watch?v=mV59ZmSHU9Q&feature=youtu.be
Ссылка на презентацию: [console@nodeschoolspb.pdf](https://github.com/nodeschool/spb/files/4874924/console%40nodeschoolspb.pdf)
Ссылка на файлы скриптов из презентации: https://github.com/zeckson/tips-and-tricks/tree/master/shell
